import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  heading: { gap: 9 },
  field: { gap: 7 },
  fields: { gap: 14 },
  records: { gap: 12 },
  advanced: { gap: 16 },
  sources: { gap: 6 },
  disabled: { opacity: .45 },
  emptyCopy: { textAlign: `center` },
  skeletonName: { width: `70%`, height: 20 },
  compactPage: { padding: 20, paddingTop: 28 },
  page: { gap: 20, padding: 28, paddingTop: 40 },
  primaryButtonText: { color: palette.contrast },
  selectedChoiceText: { color: palette.accent },
  primaryButton: { borderColor: palette.accent, backgroundColor: palette.accent },
  selectedChoice: { borderColor: palette.accent, backgroundColor: palette.subtle },
  pasteInput: { minHeight: 140, textAlignVertical: `top`, fontSize: 11 },
  skeleton: { height: 14, borderRadius: 3, backgroundColor: palette.skeleton },
  title: { fontSize: 30, color: palette.ink, letterSpacing: -.8, fontFamily: `DMSans_700Bold` },
  label: { fontSize: 11, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  sectionTitle: { fontSize: 13, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  noticeTitle: { fontSize: 12, color: palette.warning, fontFamily: `DMSans_600SemiBold` },
  description: { fontSize: 12, lineHeight: 20, color: palette.muted, fontFamily: `DMSans_400Regular` },
  hint: { fontSize: 10, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  buttonText: { fontSize: 12, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  choiceText: { fontSize: 10, color: palette.muted, fontFamily: `DMSans_500Medium` },
  textButtonText: { fontSize: 11, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  eyebrowText: { fontSize: 9, letterSpacing: 1.5, color: palette.accent, fontFamily: `DMSans_700Bold` },
  emptyTitle: { fontSize: 18, color: palette.ink, textAlign: `center`, fontFamily: `DMSans_600SemiBold` },
  eyebrow: { gap: 7, flexDirection: `row`, alignItems: `center` },
  pagination: { gap: 12, alignItems: `center` },
  actions: { gap: 8, marginTop: 7, flexWrap: `wrap`, flexDirection: `row` },
  choices: { gap: 8, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  sectionHeading: { gap: 12, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  queryInput: { flex: 1, minWidth: 0, fontSize: 13, paddingVertical: 12, color: palette.ink, fontFamily: `DMSans_400Regular` },
  input: { minHeight: 44, borderWidth: 1, borderRadius: 5, padding: 12, fontSize: 12, color: palette.ink, borderColor: palette.line, backgroundColor: palette.input, fontFamily: `DMSans_400Regular` },
  notice: { gap: 8, padding: 16, borderWidth: 1, borderRadius: 6, borderColor: palette.line, backgroundColor: palette.input },
  panel: { gap: 14, padding: 18, borderWidth: 1, borderRadius: 6, borderColor: palette.line, backgroundColor: palette.paper },
  choice: { minHeight: 36, paddingVertical: 9, paddingHorizontal: 12, borderWidth: 1, borderRadius: 4, borderColor: palette.line, backgroundColor: palette.input },
  textButton: { gap: 6, minHeight: 40, flexDirection: `row`, alignItems: `center` },
  queryWrap: { gap: 9, minHeight: 44, paddingHorizontal: 12, borderWidth: 1, borderRadius: 5, borderColor: palette.line, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.input },
  button: { gap: 7, minHeight: 44, paddingVertical: 12, paddingHorizontal: 14, borderWidth: 1, borderRadius: 5, borderColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.paper },
  empty: { gap: 14, padding: 26, borderWidth: 1, borderRadius: 6, borderColor: palette.line, alignItems: `center`, backgroundColor: palette.paper },
});
