import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  root: { gap: 12, width: `100%`, minWidth: 0, alignSelf: `stretch` },
  status: { gap: 8, minHeight: 24, flexDirection: `row`, alignItems: `center` },
  statusIcon: { width: 24, height: 24, borderRadius: 7, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  statusLabel: { fontSize: 12, lineHeight: 20, color: palette.muted, fontFamily: `DMSans_500Medium` },
  preview: { gap: 12, width: `100%`, minWidth: 0 },
  widePreview: { flexDirection: `row`, alignItems: `stretch` },
  controls: { gap: 12, minWidth: 0 },
  wideControls: { flex: 1 },
  introRow: { gap: 12, minWidth: 0 },
  wideIntroRow: { flexDirection: `row`, alignItems: `flex-end` },
  intro: { gap: 10, minWidth: 0 },
  wideIntro: { flex: 1 },
  compactIntro: { gap: 8 },
  bar: { height: 8, borderRadius: 4, backgroundColor: palette.skeleton },
  eyebrow: { width: 98 },
  title: { width: `78%`, height: 32, borderRadius: 6 },
  compactTitle: { height: 28 },
  description: { width: `90%` },
  shortDescription: { width: `62%` },
  recents: { gap: 8, padding: 12, borderWidth: 1, borderRadius: 10, borderColor: palette.line, backgroundColor: palette.paper },
  wideRecents: { width: 224, flexShrink: 0 },
  headingRow: { gap: 10, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  recentLabel: { width: 65, height: 12 },
  recentAction: { width: 24, height: 12 },
  recentRow: { gap: 6, flexDirection: `row` },
  recentPill: { flex: 1, height: 20, borderRadius: 6 },
  shortRecentPill: { flex: .7 },
  form: { gap: 10, padding: 16, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper },
  compactForm: { gap: 8, padding: 12 },
  formLabel: { width: `30%`, height: 10 },
  formStatus: { width: `18%` },
  formRow: { gap: 10, flexDirection: `row`, alignItems: `center` },
  input: { flex: 1, height: 44, borderRadius: 8 },
  compactInput: { height: 38 },
  submit: { width: 88, height: 44, borderRadius: 8 },
  compactSubmit: { width: 72, height: 38 },
  formHint: { width: `52%` },
  formLink: { width: `20%` },
  shelf: { gap: 10, minWidth: 0, marginTop: `auto` },
  shelfTitle: { width: 126, height: 12 },
  shelfAction: { width: 54, height: 12 },
  filters: { gap: 6, flexDirection: `row`, alignItems: `center` },
  filter: { flex: 1, height: 24, maxWidth: 84, borderRadius: 7 },
  pillRows: { gap: 8 },
  pillRow: { gap: 8, flexDirection: `row` },
  offsetRow: { paddingLeft: 18 },
  pill: { flex: 1, gap: 8, height: 34, minWidth: 0, paddingHorizontal: 10, borderWidth: 1, borderRadius: 7, flexDirection: `row`, alignItems: `center`, borderColor: palette.line, backgroundColor: palette.paper },
  pillDot: { width: 5, height: 5, borderRadius: 3 },
  pillName: { flex: 1, height: 8 },
  pillPrice: { width: 30, height: 8 },
  sidebar: { gap: 12, width: 320, flexShrink: 0 },
  sidebarTitle: { width: 138, height: 16 },
  sidebarCount: { width: 38, height: 10 },
  sidebarFilters: { gap: 6, flexDirection: `row` },
  sidebarFilter: { flex: 1, height: 28, borderRadius: 7 },
  sidebarDescription: { width: `76%` },
  sidebarCards: { gap: 12, flexGrow: 1, justifyContent: `flex-end` },
  sidebarCard: { gap: 9, height: 84, padding: 12, borderWidth: 1, borderRadius: 9, justifyContent: `space-between`, borderColor: palette.line, backgroundColor: palette.paper },
  cardName: { width: `66%`, height: 14 },
  cardBadge: { width: 38, height: 14, borderRadius: 4 },
  cardPrice: { width: `38%`, height: 12 },
  cardRegistrar: { width: `26%`, height: 8 },
  resultsPanel: { padding: 16, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper },
  comparisons: { gap: 12, flexDirection: `row` },
  comparison: { flex: 1, gap: 14, minWidth: 0, padding: 16, borderWidth: 1, borderRadius: 10, borderColor: palette.line, backgroundColor: palette.input },
  compactComparison: { gap: 10, padding: 12 },
  comparisonTitle: { width: `76%`, height: 20, borderRadius: 5 },
  comparisonRows: { gap: 12 },
  comparisonRow: { gap: 10, paddingTop: 12, borderTopWidth: 1, borderTopColor: palette.line },
  registrar: { width: `42%`, height: 10 },
  availability: { width: `28%`, height: 8 },
  prices: { gap: 14, flexDirection: `row` },
  price: { flex: 1, gap: 6 },
  priceLabel: { width: `54%`, height: 8 },
  priceAmount: { width: `78%`, height: 18 },
  comparisonAction: { width: `46%`, height: 10 },
});
