import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  overlay: { flex: 1, padding: 18, backgroundColor: palette.overlay },
  keyboard: { flex: 1, alignItems: `center`, justifyContent: `center` },
  dialog: { width: `100%`, maxWidth: 600, maxHeight: `100%`, flexShrink: 1, borderRadius: 10, backgroundColor: palette.paper },
  header: { gap: 16, padding: 22, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  heading: { gap: 7, flex: 1 },
  eyebrow: { color: palette.accent, fontSize: 9, letterSpacing: 1.2, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: 28, letterSpacing: -.7, fontFamily: `DMSans_700Bold` },
  iconButton: { padding: 9, borderRadius: 6, backgroundColor: palette.input },
  steps: { gap: 8, paddingHorizontal: 22, paddingBottom: 18, flexDirection: `row`, flexWrap: `wrap`, borderBottomWidth: 1, borderBottomColor: palette.line },
  step: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_500Medium` },
  activeStep: { color: palette.accent, fontFamily: `DMSans_700Bold` },
  scroll: { flexShrink: 1 },
  content: { gap: 16, padding: 22 },
  group: { gap: 16 },
  description: { color: palette.muted, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  label: { flexShrink: 1, color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  choice: { gap: 12, padding: 18, borderWidth: 1, borderRadius: 6, borderColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  selectedChoice: { borderColor: palette.accent, backgroundColor: palette.subtle },
  choiceLabel: { flexShrink: 1, color: palette.ink, fontSize: 16, fontFamily: `DMSans_700Bold` },
  guide: { gap: 9, padding: 16, borderWidth: 1, borderRadius: 6, borderColor: palette.line, backgroundColor: palette.input },
  textButton: { gap: 6, paddingVertical: 5, flexDirection: `row`, alignItems: `center` },
  linkText: { flexShrink: 1, color: palette.accent, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  input: { minWidth: 0, minHeight: 44, padding: 12, borderWidth: 1, borderRadius: 6, borderColor: palette.line, backgroundColor: palette.input, color: palette.ink, fontSize: 13, fontFamily: `DMSans_400Regular` },
  notesInput: { minHeight: 72, textAlignVertical: `top` },
  domainFields: { gap: 15, padding: 16, borderWidth: 1, borderRadius: 6, borderColor: palette.line },
  domainHeading: { gap: 12, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  field: { gap: 7 },
  secondaryButton: { gap: 7, maxWidth: `100%`, paddingVertical: 12, paddingHorizontal: 15, borderWidth: 1, borderRadius: 6, borderColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `center` },
  secondaryText: { flexShrink: 1, color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  primaryButton: { gap: 7, flex: 1, paddingVertical: 12, paddingHorizontal: 15, borderRadius: 6, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.accent },
  primaryText: { flexShrink: 1, color: palette.contrast, fontSize: 12, fontFamily: `DMSans_700Bold` },
  disabled: { opacity: .45 },
  footer: { gap: 12, padding: 22, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `flex-end` },
  error: { padding: 12, borderRadius: 6, color: palette.danger, backgroundColor: palette.dangerBackground, fontSize: 12, lineHeight: 19 },
  success: { padding: 12, borderRadius: 6, color: palette.success, backgroundColor: palette.successBackground, fontSize: 12, lineHeight: 19 },
});
