import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  root: { gap: 28, width: `100%`, maxWidth: 1180, alignSelf: `center`, paddingHorizontal: 24, paddingVertical: 40 },
  header: { gap: 10 },
  eyebrow: { fontSize: 10, letterSpacing: 1.7, color: palette.accent, fontFamily: `DMSans_700Bold` },
  title: { fontSize: 36, letterSpacing: -1.2, color: palette.ink, fontFamily: `DMSans_700Bold` },
  description: { fontSize: 13, lineHeight: 23, maxWidth: 660, color: palette.muted, fontFamily: `DMSans_400Regular` },
  localNote: { gap: 8, padding: 12, borderRadius: 8, flexDirection: `row`, alignItems: `flex-start`, backgroundColor: palette.subtle },
  noteText: { flex: 1, color: palette.muted, fontSize: 11, lineHeight: 19, fontFamily: `DMSans_400Regular` },
  columns: { gap: 24, flexDirection: `row`, alignItems: `flex-start` },
  compactColumns: { flexDirection: `column` },
  feed: { gap: 16, flex: 1, minWidth: 0 },
  compactFeed: { width: `100%`, flex: 0 },
  people: { gap: 14, width: 290 },
  compactPeople: { width: `100%` },
  panel: { gap: 15, padding: 22, borderRadius: 12, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper },
  panelTitle: { fontSize: 16, color: palette.ink, fontFamily: `DMSans_700Bold` },
  panelHeader: { gap: 10, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  caption: { color: palette.muted, fontSize: 11, lineHeight: 19, fontFamily: `DMSans_400Regular` },
  composerFooter: { gap: 14, flexDirection: `row`, flexWrap: `wrap`, justifyContent: `space-between`, alignItems: `center` },
  audiences: { gap: 5, flexDirection: `row`, flexWrap: `wrap` },
  audience: { gap: 5, paddingVertical: 8, paddingHorizontal: 9, borderRadius: 6, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.input },
  audienceActive: { backgroundColor: palette.subtle },
  audienceLabel: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_600SemiBold` },
  audienceActiveLabel: { color: palette.accent },
  action: { gap: 7, paddingVertical: 10, paddingHorizontal: 14, borderRadius: 7, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.accent },
  actionLabel: { color: palette.contrast, fontSize: 11, fontFamily: `DMSans_700Bold` },
  secondaryAction: { gap: 6, paddingVertical: 8, paddingHorizontal: 11, borderRadius: 7, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.subtle },
  secondaryLabel: { color: palette.accent, fontSize: 11, fontFamily: `DMSans_600SemiBold` },
  disabled: { opacity: .5 },
  tabs: { gap: 6, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center` },
  tab: { gap: 7, paddingVertical: 11, paddingHorizontal: 13, borderRadius: 7, flexDirection: `row`, alignItems: `center` },
  activeTab: { backgroundColor: palette.subtle },
  tabLabel: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  activeTabLabel: { color: palette.accent },
  refresh: { padding: 9, borderRadius: 6 },
  empty: { gap: 10, padding: 28, borderRadius: 12, alignItems: `center`, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper },
  emptyTitle: { color: palette.ink, textAlign: `center`, fontSize: 16, fontFamily: `DMSans_700Bold` },
  emptyText: { color: palette.muted, textAlign: `center`, maxWidth: 360, fontSize: 12, lineHeight: 21, fontFamily: `DMSans_400Regular` },
  card: { gap: 18, padding: 22, borderRadius: 12, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper },
  cardTop: { gap: 11, flexDirection: `row`, alignItems: `center` },
  avatar: { width: 40, height: 40, borderRadius: 20, alignItems: `center`, justifyContent: `center` },
  avatarText: { fontSize: 16, fontFamily: `DMSans_700Bold` },
  person: { gap: 3, flex: 1, minWidth: 0 },
  name: { color: palette.ink, fontSize: 13, fontFamily: `DMSans_700Bold` },
  metadata: { gap: 5, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center` },
  metaLabel: { color: palette.muted, fontSize: 10, lineHeight: 17, fontFamily: `DMSans_400Regular` },
  personCard: { gap: 13, padding: 18, borderRadius: 10, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper },
  biography: { fontSize: 12, lineHeight: 20, color: palette.muted, fontFamily: `DMSans_400Regular` },
  domains: { gap: 7, paddingTop: 12, borderTopWidth: 1, borderTopColor: palette.line },
  domain: { gap: 6, paddingVertical: 5, flexDirection: `row`, alignItems: `center` },
  domainDetails: { gap: 2, flex: 1, minWidth: 0 },
  domainExternal: { flexShrink: 0 },
  domainHeading: { gap: 4, minWidth: 0, flexDirection: `row`, alignItems: `center` },
  domainName: { minWidth: 0, fontSize: 11, flexShrink: 1, color: palette.ink, fontFamily: `DMSans_500Medium` },
  domainDescription: { flex: 1, minWidth: 0, fontSize: 11, color: `#ffffff`, fontFamily: `DMSans_400Regular` },
  moreDomains: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_400Regular` },
  deletion: { gap: 6, paddingVertical: 5, paddingHorizontal: 7, borderRadius: 5, flexDirection: `row`, alignItems: `center` },
  deleteLabel: { color: palette.danger, fontSize: 10, fontFamily: `DMSans_600SemiBold` },
  deletionRow: { gap: 5, flexDirection: `row`, flexWrap: `wrap`, justifyContent: `flex-end`, alignItems: `center` },
  skeleton: { height: 14, width: `75%`, borderRadius: 5, backgroundColor: palette.skeleton },
  skeletonAvatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: palette.skeleton },
  skeletonBody: { gap: 10 },
  skeletonWide: { width: `100%` },
  skeletonShort: { width: `45%` },
  skeletonName: { width: 130 },
});
