import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  sections: { width: `100%`, backgroundColor: palette.paper },
  section: { width: `100%`, borderTopWidth: 1, paddingVertical: 64, paddingHorizontal: 32, borderTopColor: palette.line },
  compactSection: { paddingVertical: 44, paddingHorizontal: 20 },
  alternateSection: { backgroundColor: palette.subtle },
  inner: { gap: 26, width: `100%`, maxWidth: 1056, alignSelf: `center` },
  heading: { gap: 11, flexShrink: 1, maxWidth: 600 },
  eyebrow: { fontSize: 9, letterSpacing: 1.6, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  title: { fontSize: 28, lineHeight: 35, letterSpacing: -.7, color: palette.ink, fontFamily: `DMSans_700Bold` },
  description: { fontSize: 13, lineHeight: 22, maxWidth: 580, color: palette.muted, fontFamily: `DMSans_400Regular` },
  grid: { gap: 14, flexWrap: `wrap`, flexDirection: `row`, alignItems: `stretch` },
  cardBacking: { ...StyleSheet.absoluteFillObject, zIndex: 0, transform: [{ translateX: 7 }, { translateY: 6 }] },
  cardForeground: { ...StyleSheet.absoluteFillObject, zIndex: 0 },
  cardTop: { gap: 12, zIndex: 1, alignItems: `center`, flexDirection: `row`, justifyContent: `space-between` },
  basicCard: { gap: 16, padding: 23, borderWidth: 1, position: `relative`, borderColor: `transparent`, backgroundColor: `transparent` },
  cardLabel: { zIndex: 1, fontSize: 10, letterSpacing: .5, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  cardTitle: { zIndex: 1, fontSize: 17, lineHeight: 23, color: palette.ink, fontFamily: `DMSans_700Bold` },
  cardDescription: { zIndex: 1, fontSize: 12, lineHeight: 21, color: palette.muted, fontFamily: `DMSans_400Regular` },
  example: { zIndex: 1, fontSize: 11, marginTop: `auto`, paddingTop: 13, borderTopWidth: 1, color: palette.accent, borderTopColor: palette.line, fontFamily: `DMSans_500Medium` },
  sectionAction: { alignItems: `flex-start` },
  button: { gap: 7, zIndex: 1, minHeight: 42, borderWidth: 1, borderRadius: 3, paddingVertical: 12, paddingHorizontal: 16, alignSelf: `flex-start`, alignItems: `center`, flexDirection: `row`, borderColor: palette.accent, backgroundColor: palette.accent },
  secondaryButton: { backgroundColor: `transparent` },
  smallButton: { minHeight: 34, paddingVertical: 9, paddingHorizontal: 12 },
  buttonText: { fontSize: 11, color: palette.contrast, fontFamily: `DMSans_700Bold` },
  secondaryButtonText: { color: palette.accent },
  pressed: { opacity: .65 },
  cta: { gap: 24 },
  ctaCopy: { gap: 13, flexShrink: 1, maxWidth: 680 },
  wideCta: { gap: 36, alignItems: `center`, flexDirection: `row`, justifyContent: `space-between` },
  ctaActions: { gap: 18, width: 312, maxWidth: `100%`, alignItems: `flex-start` },
  wideCtaActions: { flexShrink: 0, alignItems: `flex-end` },
  ctaActivityGrid: { gap: 4, width: `100%` },
  ctaActivityRow: { gap: 4, flexDirection: `row` },
  ctaActivityCell: { flex: 1, aspectRatio: 1, borderRadius: 999 },
  ctaActionLink: { alignSelf: `flex-start` },
  wideCtaActionLink: { alignSelf: `flex-end` },
  note: { fontSize: 10, lineHeight: 17, color: palette.muted, fontFamily: `DMSans_400Regular` },
  pricingHeadingRow: { gap: 32 },
  widePricingHeadingRow: { alignItems: `center`, flexDirection: `row` },
  pricingHeadingCopy: { minWidth: 0, flexShrink: 1 },
  widePricingHeadingCopy: { flex: 1 },
  pricingActivityGrid: { gap: 4, minWidth: 0, width: `100%`, maxWidth: 440 },
  widePricingActivityGrid: { width: `40%`, flexShrink: 0 },
  pricingActivityRow: { gap: 4, flexDirection: `row` },
  pricingActivityCell: { flex: 1, aspectRatio: 1, borderRadius: 3 },
  plan: { gap: 15, padding: 24, borderWidth: 1, position: `relative`, borderColor: `transparent`, backgroundColor: `transparent` },
  planStatus: { fontSize: 9, paddingVertical: 5, paddingHorizontal: 7, borderRadius: 3, color: palette.accent, backgroundColor: `${palette.accent}14`, fontFamily: `DMSans_600SemiBold` },
  price: { zIndex: 1, fontSize: 38, lineHeight: 45, marginTop: 7, letterSpacing: -1, color: palette.ink, fontFamily: `DMSans_700Bold` },
  plannedPrice: { fontSize: 24, lineHeight: 45, letterSpacing: -.4 },
  features: { gap: 13, flex: 1, zIndex: 1, marginVertical: 7, paddingTop: 19, borderTopWidth: 1, borderTopColor: palette.line },
  feature: { gap: 8, alignItems: `flex-start`, flexDirection: `row` },
  featureText: { flex: 1, fontSize: 11, lineHeight: 17, color: palette.ink, fontFamily: `DMSans_400Regular` },
  plannedFeatureText: { color: palette.muted },
  finalCta: { gap: 15, alignItems: `center` },
  centeredText: { textAlign: `center` },
  finalActions: { gap: 12, marginTop: 9, flexWrap: `wrap`, flexDirection: `row`, justifyContent: `center` },
});
