import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette, compact: boolean, condensed: boolean, roomy: boolean) => StyleSheet.create({
  root: { gap: compact || condensed ? 18 : 26, flex: compact ? undefined : 1, minWidth: 0, padding: compact ? 18 : condensed ? 24 : 32, borderWidth: compact ? 1 : 0, borderRadius: compact ? 16 : 0, overflow: `hidden`, borderColor: palette.line, backgroundColor: compact ? palette.subtle : `transparent`, justifyContent: `center` },
  art: { top: 0, right: 0, width: 370, height: condensed ? 226 : 276, zIndex: 0, overflow: `hidden`, position: `absolute` },
  artFade: { ...StyleSheet.absoluteFillObject, zIndex: 1 },
  artScene: { top: -34, right: -120, width: 490, height: condensed ? 260 : 310, opacity: condensed ? .25 : .35, position: `absolute` },
  heading: { gap: compact || condensed ? 10 : 16, zIndex: 1, maxWidth: 620 },
  eyebrowRow: { gap: 8, flexDirection: `row`, alignItems: `center` },
  eyebrow: { color: palette.accent, fontSize: 9, letterSpacing: 1.4, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: compact ? 28 : condensed ? 36 : roomy ? 52 : 40, lineHeight: compact ? 32 : condensed ? 40 : roomy ? 56 : 44, letterSpacing: compact ? -.8 : -1.8, fontFamily: `DMSans_700Bold` },
  accent: { color: palette.accent, fontStyle: `italic` },
  description: { color: palette.muted, maxWidth: 510, fontSize: compact ? 12 : 14, lineHeight: compact ? 19 : 23, fontFamily: `DMSans_400Regular` },
  preview: { gap: condensed ? 8 : 10, zIndex: 1, padding: condensed ? 14 : 16, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper },
  previewHeading: { gap: 12, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  previewLabelRow: { gap: 7, flexDirection: `row`, alignItems: `center` },
  previewLabel: { color: palette.ink, fontSize: 11, fontFamily: `DMSans_700Bold` },
  previewTag: { color: palette.muted, fontSize: 9, fontFamily: `DMSans_500Medium` },
  search: { gap: 10, minHeight: 38, paddingHorizontal: 11, borderWidth: 1, borderRadius: 7, flexDirection: `row`, alignItems: `center`, borderColor: palette.line, backgroundColor: palette.input },
  searchQuery: { flex: 1, minWidth: 0, color: palette.muted, fontSize: 11, fontFamily: `DMSans_500Medium` },
  searchExtensions: { color: palette.accent, fontSize: 9, fontFamily: `DMSans_600SemiBold` },
  records: { gap: condensed ? 4 : 6 },
  record: { gap: 10, paddingVertical: condensed ? 4 : 5, flexDirection: `row`, alignItems: `center` },
  recordSymbol: { width: 26, height: 26, borderRadius: 7, backgroundColor: palette.subtle, alignItems: `center`, justifyContent: `center` },
  recordCopy: { gap: 2, flex: 1, minWidth: 0 },
  recordName: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  recordNote: { color: palette.muted, fontSize: 9, fontFamily: `DMSans_400Regular` },
  recordLabel: { paddingVertical: 4, paddingHorizontal: 7, borderRadius: 4, color: palette.accent, backgroundColor: palette.subtle, fontSize: 9, fontFamily: `DMSans_500Medium` },
  previewNote: { gap: 10, paddingTop: 8, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: `row`, alignItems: `center` },
  previewNoteText: { flex: 1, color: palette.muted, fontSize: 9, lineHeight: 14, fontFamily: `DMSans_400Regular` },
  benefits: { gap: 14, zIndex: 1, paddingTop: 16, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: `row` },
  benefit: { gap: 7, flex: 1, minWidth: 0 },
  benefitHeading: { gap: 6, flexDirection: `row`, alignItems: `center`, flexWrap: `wrap` },
  benefitLabel: { color: palette.ink, fontSize: 11, fontFamily: `DMSans_700Bold` },
  benefitCopy: { color: palette.muted, fontSize: 11, lineHeight: 17, fontFamily: `DMSans_400Regular` },
});
