import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  list: { gap: 12 },
  countSkeleton: { width: 58, height: 20, borderRadius: 6, backgroundColor: palette.skeleton },
  messageError: { color: palette.danger },
  scroll: { minHeight: 0, flexGrow: 0, flexShrink: 1 },
  message: { fontSize: 12, lineHeight: 20, paddingVertical: 14, color: palette.muted, fontFamily: `DMSans_400Regular` },
  footer: { paddingTop: 12, flexShrink: 0, borderTopWidth: 1, borderTopColor: palette.line },
  footerLinkText: { fontSize: 12, color: palette.accent, fontFamily: `DMSans_700Bold` },
  footerLink: { gap: 8, minHeight: 44, borderRadius: 6, paddingVertical: 10, paddingHorizontal: 12, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  button: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderRadius: 6,
    alignItems: `center`,
    justifyContent: `center`,
    borderColor: palette.line,
    backgroundColor: palette.subtle,
  },
  pressed: { opacity: .75 },
  badge: {
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderWidth: 2,
    borderRadius: 9,
    position: `absolute`,
    paddingHorizontal: 3,
    alignItems: `center`,
    justifyContent: `center`,
    borderColor: palette.paper,
    backgroundColor: `#187565`,
  },
  badgeText: {
    fontSize: 9,
    color: `#ffffff`,
    fontFamily: `DMSans_700Bold`,
  },
  overlay: {
    flex: 1,
    paddingHorizontal: 20,
    alignItems: `center`,
    justifyContent: `center`,
  },
  backdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: palette.overlay,
  },
  panel: {
    gap: 14,
    width: `100%`,
    padding: 16,
    maxWidth: 440,
    minHeight: 0,
    maxHeight: `85%`,
    flexShrink: 1,
    borderWidth: 1,
    borderRadius: 12,
    overflow: `hidden`,
    borderColor: palette.line,
    backgroundColor: palette.paper,
  },
  heading: {
    gap: 8,
    flexShrink: 0,
    flexDirection: `row`,
    alignItems: `center`,
  },
  title: {
    flex: 1,
    fontSize: 16,
    color: palette.ink,
    fontFamily: `DMSans_700Bold`,
  },
  count: {
    fontSize: 10,
    borderRadius: 6,
    paddingVertical: 5,
    color: palette.accent,
    paddingHorizontal: 8,
    backgroundColor: palette.subtle,
    fontFamily: `DMSans_600SemiBold`,
  },
  close: {
    width: 40,
    height: 40,
    borderRadius: 6,
    alignItems: `center`,
    justifyContent: `center`,
    backgroundColor: palette.input,
  },
});
