import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  list: { gap: 12 },
  scroll: { flexGrow: 0, flexShrink: 1 },
  button: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderRadius: 6,
    alignItems: `center`,
    justifyContent: `center`,
    borderColor: palette.line,
    backgroundColor: palette.subtle,
  },
  pressed: { opacity: .75 },
  badge: {
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderWidth: 2,
    borderRadius: 9,
    position: `absolute`,
    paddingHorizontal: 3,
    alignItems: `center`,
    justifyContent: `center`,
    borderColor: palette.paper,
    backgroundColor: palette.accent,
  },
  badgeText: {
    fontSize: 9,
    color: palette.contrast,
    fontFamily: `DMSans_700Bold`,
  },
  overlay: {
    flex: 1,
    paddingHorizontal: 20,
    alignItems: `center`,
    justifyContent: `center`,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: palette.overlay,
  },
  panel: {
    gap: 14,
    width: `100%`,
    padding: 16,
    maxWidth: 440,
    maxHeight: `85%`,
    borderWidth: 1,
    borderRadius: 12,
    borderColor: palette.line,
    backgroundColor: palette.paper,
  },
  heading: {
    gap: 8,
    flexDirection: `row`,
    alignItems: `center`,
  },
  title: {
    flex: 1,
    fontSize: 16,
    color: palette.ink,
    fontFamily: `DMSans_700Bold`,
  },
  count: {
    fontSize: 10,
    borderRadius: 6,
    paddingVertical: 5,
    color: palette.accent,
    paddingHorizontal: 8,
    backgroundColor: palette.subtle,
    fontFamily: `DMSans_600SemiBold`,
  },
  close: {
    width: 40,
    height: 40,
    borderRadius: 6,
    alignItems: `center`,
    justifyContent: `center`,
    backgroundColor: palette.input,
  },
});
