import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  actionsCell: { minHeight: 20 },
  statusDotWrap: { width: 12, alignItems: `center` },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  rowStatus: { gap: 6, flexDirection: `row`, alignItems: `center` },
  statusText: { flex: 1, color: palette.muted, fontSize: 11, lineHeight: 18, fontFamily: `DMSans_500Medium` },
  provider: { gap: 12, minWidth: 0 },
  tabs: { gap: 6, padding: 6, minWidth: 0, borderWidth: 1, borderRadius: 8, flexWrap: `wrap`, borderColor: palette.line, flexDirection: `row`, backgroundColor: palette.input },
  tab: { gap: 7, flexGrow: 1, minWidth: 100, minHeight: 44, borderWidth: 1, borderRadius: 6, paddingVertical: 10, borderBottomWidth: 2, paddingHorizontal: 12, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, borderColor: `transparent`, backgroundColor: `transparent` },
  activeTab: { borderBottomColor: palette.accent, backgroundColor: palette.subtle },
  tabText: { flexShrink: 1, fontSize: 11, color: palette.muted, fontFamily: `DMSans_600SemiBold` },
  activeTabText: { color: palette.accent },
  embedded: { padding: 0, borderWidth: 0, backgroundColor: `transparent` },
  account: { gap: 8, padding: 16, borderWidth: 1, borderRadius: 10, borderColor: palette.line, backgroundColor: palette.input },
  panel: { gap: 22, padding: 24, borderRadius: 12, borderWidth: 1, borderColor: palette.line, backgroundColor: palette.paper },
  row: { gap: 12, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center` },
  title: { flex: 1, minWidth: 0, color: palette.ink, fontSize: 15, fontFamily: `DMSans_700Bold` },
  copy: { color: palette.muted, fontSize: 11, lineHeight: 19, fontFamily: `DMSans_400Regular` },
  field: { gap: 8 },
  syncStatus: { gap: 8, flexDirection: `row`, alignItems: `center` },
  label: { flexShrink: 1, color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  inputWrap: { position: `relative` },
  publicInput: { paddingRight: 12 },
  revealButton: { top: 6, right: 6, width: 44, height: 44, position: `absolute`, borderRadius: 6, alignItems: `center`, justifyContent: `center` },
  input: { minWidth: 0, minHeight: 56, maxHeight: 180, borderWidth: 1, borderRadius: 8, borderColor: palette.line, backgroundColor: palette.input, padding: 12, paddingRight: 62, fontSize: 12, color: palette.ink, fontFamily: `monospace` },
  skeleton: { height: 56, borderRadius: 8, backgroundColor: palette.skeleton },
  button: { gap: 8, maxWidth: `100%`, padding: 12, borderRadius: 6, flexDirection: `row`, alignItems: `center`, borderWidth: 1, borderColor: palette.line },
  primary: { backgroundColor: palette.accent, borderColor: palette.accent },
  primaryText: { color: palette.contrast },
  disabled: { opacity: 0.55 },
  buttonText: { flexShrink: 1, color: palette.ink, fontSize: 11, fontFamily: `DMSans_600SemiBold` },
  viewDomainsText: { flexShrink: 1, color: palette.success, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  viewDomainsButton: { gap: 8, minHeight: 44, maxWidth: `100%`, paddingHorizontal: 14, borderWidth: 1, borderRadius: 6, borderColor: palette.success, backgroundColor: palette.successBackground, flexDirection: `row`, alignSelf: `flex-start`, alignItems: `center`, justifyContent: `center` },
  reviewSection: { gap: 12, marginTop: 8, padding: 16, borderWidth: 1, borderRadius: 10, borderColor: palette.line, backgroundColor: palette.input },
  reviewHeading: { gap: 8, flexDirection: `row`, alignItems: `center` },
  candidateCopy: { gap: 4, flex: 1, minWidth: 0, flexBasis: 180 },
  candidateRow: { gap: 12, paddingTop: 12, borderTopWidth: 1, borderColor: palette.line, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center` },
  candidateName: { color: palette.ink, fontSize: 13, fontFamily: `DMSans_600SemiBold` },
  candidateDetails: { color: palette.muted, fontSize: 11, lineHeight: 18, fontFamily: `DMSans_400Regular` },
  candidateSource: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_500Medium` },
  includeText: { flexShrink: 1, color: palette.accent, fontSize: 11, fontFamily: `DMSans_600SemiBold` },
  includeButton: { gap: 7, maxWidth: `100%`, padding: 10, borderWidth: 1, borderRadius: 6, borderColor: palette.line, backgroundColor: palette.paper, flexDirection: `row`, alignItems: `center` },
  note: { gap: 10, flexDirection: `row`, alignItems: `center` },
  noteText: { flex: 1, color: palette.muted, fontSize: 11, lineHeight: 19, fontFamily: `DMSans_400Regular` },
});
