import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  root: { gap: 44, minWidth: 0 },
  section: { gap: 20, minWidth: 0 },
  bandHeading: { gap: 12, minWidth: 0 },
  bandTitle: { color: `#ffffff` },
  bandEyebrow: { color: `#ffe7e9` },
  bandDescription: { color: `#ffedf0` },
  ctaBand: { minWidth: 0, overflow: `hidden`, position: `relative`, paddingVertical: 40, backgroundColor: `#8054d7` },
  youtubeBand: { overflow: `hidden`, position: `relative`, paddingVertical: 40, backgroundColor: `#d83b42` },
  bandPattern: { top: 0, left: 0, right: 0, bottom: 0, position: `absolute`, pointerEvents: `none` },
  bandRing: { position: `absolute`, borderWidth: 1, borderColor: `rgba(255,255,255,.16)` },
  outerRing: { top: -270, right: -220, width: 620, height: 620, borderRadius: 310 },
  innerRing: { top: -160, right: -110, width: 400, height: 400, borderRadius: 200 },
  cornerRing: { left: -160, bottom: -210, width: 400, height: 400, borderRadius: 200 },
  pressed: { opacity: .75 },
  disabled: { opacity: .5 },
  icon: { flexShrink: 0 },
  ctaCopy: { gap: 12, flex: 1, minWidth: 0 },
  ctaActions: { gap: 12, maxWidth: `100%`, alignItems: `flex-start` },
  cta: { gap: 24, padding: 28, borderWidth: 1, borderRadius: 12, borderColor: palette.line, backgroundColor: palette.paper },
  wideCta: { flexDirection: `row`, alignItems: `center` },
  ctaTitle: { fontSize: 32, lineHeight: 38, color: palette.ink, fontFamily: `InstrumentSerif_400Regular` },
  description: { maxWidth: 720, fontSize: 13, lineHeight: 22, color: palette.muted, fontFamily: `DMSans_400Regular` },
  eyebrow: { gap: 8, flexDirection: `row`, alignItems: `center` },
  eyebrowText: { fontSize: 10, letterSpacing: 1.2, color: palette.accent, fontFamily: `DMSans_700Bold` },
  heading: { gap: 12, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  titleRow: { gap: 10, minWidth: 0, flexShrink: 1, flexDirection: `row`, alignItems: `center` },
  title: { flexShrink: 1, fontSize: 27, lineHeight: 34, color: palette.ink, fontFamily: `InstrumentSerif_400Regular` },
  grid: { gap: 20, flexWrap: `wrap`, flexDirection: `row`, alignItems: `stretch` },
  button: { gap: 8, minWidth: 0, minHeight: 44, maxWidth: `100%`, padding: 12, borderWidth: 1, borderRadius: 8, borderColor: palette.line, flexDirection: `row`, alignItems: `center` },
  primary: { borderColor: palette.accent, backgroundColor: palette.accent },
  primaryText: { color: palette.contrast },
  buttonText: { flexShrink: 1, color: palette.ink, fontSize: 12, fontFamily: `DMSans_700Bold` },
  card: { gap: 12, padding: 20, borderWidth: 1, borderRadius: 12, borderColor: palette.line, backgroundColor: palette.paper },
  source: { backgroundColor: palette.input },
  cardTitle: { flexShrink: 1, fontSize: 15, lineHeight: 22, color: palette.ink, fontFamily: `DMSans_700Bold` },
  sourceDescription: { fontSize: 12, lineHeight: 20, color: palette.muted, fontFamily: `DMSans_400Regular` },
  sourceHeading: { gap: 8, flexDirection: `row`, alignItems: `center` },
  meta: { gap: 8, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  metaText: { fontSize: 10, lineHeight: 16, color: palette.muted, fontFamily: `DMSans_500Medium` },
  sourceName: { color: palette.accent },
  resourceLink: { gap: 6, marginTop: `auto`, flexDirection: `row`, alignItems: `center` },
  resourceText: { fontSize: 11, color: palette.accent, fontFamily: `DMSans_700Bold` },
  videoCard: { padding: 0, overflow: `hidden` },
  videoBody: { gap: 12, flex: 1, padding: 20 },
  thumbnail: { width: `100%`, aspectRatio: 16 / 9, backgroundColor: palette.subtle },
  videoPlaceholder: { alignItems: `center`, justifyContent: `center` },
  skeleton: { backgroundColor: palette.skeleton },
  skeletonTitle: { width: `80%`, height: 18, borderRadius: 5 },
  skeletonLine: { height: 12, borderRadius: 4 },
  status: { fontSize: 12, lineHeight: 20, color: palette.muted, fontFamily: `DMSans_400Regular` },
});
