import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  page: { gap: 28, width: `100%`, maxWidth: 1120, alignSelf: `center`, paddingTop: 28, paddingBottom: 48 },
  header: { gap: 16, width: `100%`, maxWidth: 820, alignSelf: `center` },
  back: { gap: 8, minHeight: 44, alignSelf: `flex-start`, flexDirection: `row`, alignItems: `center` },
  backText: { fontSize: 12, color: palette.muted, fontFamily: `DMSans_500Medium` },
  category: { fontSize: 10, letterSpacing: 1.2, color: palette.accent, textTransform: `uppercase`, fontFamily: `DMSans_700Bold` },
  title: { fontSize: 34, lineHeight: 41, letterSpacing: -.8, color: palette.ink, fontFamily: `InstrumentSerif_400Regular` },
  wideTitle: { fontSize: 48, lineHeight: 56, letterSpacing: -1.5 },
  description: { fontSize: 15, lineHeight: 26, color: palette.muted, fontFamily: `DMSans_400Regular` },
  meta: { gap: 14, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  authorLink: { minHeight: 44, justifyContent: `center` },
  author: { fontSize: 11, color: palette.ink, fontFamily: `DMSans_700Bold` },
  metaText: { fontSize: 11, color: palette.muted, fontFamily: `DMSans_400Regular` },
  readingTime: { gap: 6, flexDirection: `row`, alignItems: `center` },
  figure: { gap: 12 },
  image: { width: `100%`, aspectRatio: 1.6, borderWidth: 1, borderRadius: 16, borderColor: palette.line },
  caption: { fontSize: 11, lineHeight: 18, textAlign: `center`, color: palette.muted, fontFamily: `DMSans_400Regular` },
  body: { gap: 32, width: `100%`, maxWidth: 760, alignSelf: `center` },
  takeaway: { gap: 10, padding: 22, borderLeftWidth: 3, borderRadius: 10, borderLeftColor: palette.accent, backgroundColor: palette.subtle },
  takeawayLabel: { fontSize: 10, letterSpacing: .6, color: palette.accent, fontFamily: `DMSans_700Bold` },
  takeawayText: { fontSize: 15, lineHeight: 26, color: palette.ink, fontFamily: `DMSans_400Regular` },
  section: { gap: 16 },
  sectionTitle: { fontSize: 23, lineHeight: 31, letterSpacing: -.4, color: palette.ink, fontFamily: `DMSans_700Bold` },
  paragraph: { fontSize: 15, lineHeight: 28, color: palette.muted, fontFamily: `DMSans_400Regular` },
  list: { gap: 12 },
  listItem: { gap: 10, flexDirection: `row`, alignItems: `flex-start` },
  listMarker: { fontSize: 18, lineHeight: 28, color: palette.accent, fontFamily: `DMSans_700Bold` },
  listText: { flex: 1, fontSize: 15, lineHeight: 28, color: palette.muted, fontFamily: `DMSans_400Regular` },
  sources: { gap: 14, paddingTop: 28, borderTopWidth: 1, borderTopColor: palette.line },
  sourceLink: { gap: 8, minHeight: 44, flexDirection: `row`, alignItems: `center` },
  sourceText: { flexShrink: 1, fontSize: 13, lineHeight: 22, color: palette.accent, fontFamily: `DMSans_500Medium` },
  pressed: { opacity: .75 },
  portfolioLink: { gap: 12, minHeight: 48, padding: 16, borderRadius: 8, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.strong },
  portfolioText: { flex: 1, fontSize: 13, lineHeight: 20, color: `#ffffff`, fontFamily: `DMSans_600SemiBold` },
  related: { gap: 24, marginTop: 20, paddingTop: 32, borderTopWidth: 1, borderTopColor: palette.line },
  relatedTitle: { fontSize: 26, lineHeight: 34, letterSpacing: -.6, color: palette.ink, fontFamily: `DMSans_700Bold` },
  relatedGrid: { gap: 20, flexWrap: `wrap`, flexDirection: `row`, alignItems: `stretch` },
});
