import { StyleSheet } from 'react-native';
import { discoveryCardGap } from './useDiscoveryShelf';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  faded: { opacity: .55 },
  section: { gap: 12, minWidth: 0 },
  sidebarSection: { flex: 1, minHeight: 0 },
  shelf: { flex: 1, minHeight: 0 },
  pillTrack: { gap: discoveryCardGap },
  shelfTrack: { gap: discoveryCardGap, padding: 2, flexGrow: 1 },
  filledShelfGrid: { flexGrow: 1 },
  filledSidebarCard: { flexGrow: 1 },
  sidebarGrid: { gap: discoveryCardGap, flexWrap: `nowrap`, flexDirection: `column` },
  grid: { gap: 10, flexWrap: `wrap`, flexDirection: `row` },
  heading: { gap: 8, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  titleGroup: { gap: 7, minWidth: 0, flexShrink: 1, flexDirection: `row`, alignItems: `center` },
  headingTitle: { minWidth: 0, fontSize: 15, flexShrink: 1, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  count: { fontSize: 10, color: palette.muted, fontFamily: `DMSans_400Regular` },
  headingTools: { gap: 8, flexDirection: `row`, alignItems: `center` },
  cardContent: { gap: 10, minWidth: 0, flexGrow: 1 },
  fullContent: { gap: 4, justifyContent: `flex-start` },
  sidebarContent: { justifyContent: `space-between` },
  compactContent: { gap: 5, justifyContent: `space-between` },
  pillContent: { gap: 8, flex: 1, paddingRight: 34, flexDirection: `row`, alignItems: `center` },
  watchHeading: { paddingRight: 92 },
  compactWatchHeading: { paddingRight: 32 },
  watchAction: { top: 12, right: 12, zIndex: 2, position: `absolute` },
  compactWatchAction: { top: 4, right: 6 },
  pillWatchAction: { top: 6 },
  compareControl: { ...StyleSheet.absoluteFillObject, zIndex: 1, borderRadius: 10 },
  comparePressed: { backgroundColor: `${palette.accent}14` },
  filterGroup: { gap: 5, flexShrink: 0, flexWrap: `nowrap`, flexDirection: `row`, alignItems: `center` },
  filterDivider: { width: 1, height: 20, marginHorizontal: 3, backgroundColor: palette.line },
  category: { gap: 6, flexShrink: 0, minHeight: 36, borderWidth: 1, borderRadius: 7, paddingHorizontal: 12, flexDirection: `row`, alignItems: `center`, borderColor: palette.line },
  selectedCategory: { borderColor: palette.accent, backgroundColor: palette.subtle },
  categoryLabel: { fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  refresh: { gap: 5, padding: 6, flexShrink: 0, flexDirection: `row`, alignItems: `center` },
  description: { fontSize: 10, lineHeight: 16, color: palette.muted, fontFamily: `DMSans_400Regular` },
  card: { flex: 1, gap: 10, minWidth: 200, maxWidth: `100%`, flexBasis: 240, padding: 16, borderWidth: 1, borderRadius: 10, borderColor: palette.line, backgroundColor: palette.paper },
  sidebarCard: { height: 232, minWidth: 0, width: `100%`, flexGrow: 0, flexShrink: 0, flexBasis: `auto`, overflow: `hidden`, justifyContent: `space-between` },
  fullCard: { gap: 6, padding: 12 },
  compactCard: { gap: 5, height: 84, padding: 10, minWidth: 0, width: `100%`, flexGrow: 0, flexShrink: 0, flexBasis: `auto`, borderRadius: 8, overflow: `hidden`, justifyContent: `space-between` },
  pillCard: { gap: 8, height: 40, minWidth: 0, width: `100%`, flexGrow: 0, flexShrink: 0, flexBasis: `auto`, borderRadius: 6, paddingVertical: 6, paddingHorizontal: 10, overflow: `hidden`, flexDirection: `row`, alignItems: `center` },
  cardHeading: { gap: 7, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  domain: { flex: 1, minWidth: 0, fontSize: 16, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  fullDomain: { fontSize: 15, lineHeight: 18 },
  pillDomain: { fontSize: 11, lineHeight: 15 },
  compactDomain: { fontSize: 14, lineHeight: 18 },
  badges: { gap: 5, flexWrap: `wrap`, flexDirection: `row` },
  badge: { gap: 4, borderWidth: 1, borderRadius: 5, paddingVertical: 3, paddingHorizontal: 6, flexDirection: `row`, alignItems: `center` },
  badgeLabel: { fontSize: 10, fontFamily: `DMSans_500Medium` },
  compactBadge: { gap: 3, paddingVertical: 1, paddingHorizontal: 4 },
  compactBadgeLabel: { fontSize: 9, lineHeight: 13 },
  pillBadge: { flexShrink: 0, paddingVertical: 2, paddingHorizontal: 3 },
  compactMeta: { gap: 8, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  compactPriceRow: { gap: 8, minWidth: 0, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  actionsCell: { minWidth: 0, flexShrink: 1, minHeight: 14 },
  rowStatus: { gap: 4, minWidth: 0, flexShrink: 1, flexDirection: `row`, alignItems: `center` },
  statusDotWrap: { width: 10, alignItems: `center` },
  statusDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: palette.success },
  statusText: { minWidth: 0, fontSize: 9, flexShrink: 1, color: palette.success, fontFamily: `DMSans_500Medium` },
  price: { gap: 3 },
  priceAmount: { fontSize: 17, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  pillPriceAmount: { maxWidth: 104, fontSize: 10, lineHeight: 14 },
  compactPriceAmount: { minWidth: 0, flexShrink: 1, fontSize: 12, lineHeight: 16 },
  platforms: { gap: 1 },
  platformRow: { gap: 6, minHeight: 16, flexDirection: `row`, alignItems: `center` },
  platformCount: { fontSize: 9, lineHeight: 14, flexShrink: 0, color: palette.accent, fontFamily: `DMSans_500Medium` },
  platformLabel: { flex: .8, minWidth: 0, fontSize: 10, lineHeight: 16, color: palette.success, fontFamily: `DMSans_500Medium` },
  platformPrice: { flex: 1.1, minWidth: 0, fontSize: 10, lineHeight: 16, textAlign: `right`, color: palette.ink, fontFamily: `DMSans_500Medium` },
  detail: { fontSize: 9, lineHeight: 15, color: palette.muted, fontFamily: `DMSans_400Regular` },
  access: { gap: 6, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  error: { fontSize: 10, lineHeight: 16, color: palette.danger, fontFamily: `DMSans_400Regular` },
  skeleton: { height: 10, borderRadius: 4, backgroundColor: palette.skeleton },
  skeletonName: { width: `80%`, height: 15 },
  skeletonStatus: { width: `40%` },
  skeletonPrice: { width: `60%`, height: 22 },
  pillSkeletonName: { flex: 1, width: `auto`, height: 10 },
  pillSkeletonStatus: { width: 14, height: 10 },
  pillSkeletonPrice: { width: 64, height: 10 },
});
