import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette, roomy: boolean, compact: boolean) => StyleSheet.create({
  root: { gap: 20, width: `100%`, maxWidth: 1600, paddingVertical: 24, paddingHorizontal: compact ? 16 : 24, alignSelf: `center` },
  placeholder: { height: 8, borderRadius: 5, overflow: `hidden`, backgroundColor: palette.skeleton },
  heading: { gap: compact ? 14 : 22, padding: compact ? 18 : 24, borderWidth: 1, borderRadius: 18, overflow: `hidden`, borderColor: palette.line, backgroundColor: palette.paper, alignItems: `center`, flexDirection: `row` },
  headingCopy: { gap: 5, flex: 1, minWidth: 0 },
  avatar: { width: compact ? 56 : 72, height: compact ? 56 : 72, borderWidth: 1, borderRadius: 24, borderColor: palette.accent, backgroundColor: palette.subtle, alignItems: `center`, justifyContent: `center` },
  eyebrow: { color: palette.accent, fontSize: 9, letterSpacing: 1.6, fontFamily: `DMSans_700Bold` },
  label: { color: palette.ink, fontSize: compact ? 20 : 28, lineHeight: compact ? 27 : 36, letterSpacing: -.5, fontFamily: `DMSans_700Bold` },
  description: { color: palette.muted, fontSize: 12, lineHeight: 19, fontFamily: `DMSans_400Regular` },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.accent },
  dots: { gap: 7, paddingHorizontal: 10, flexDirection: `row` },
  workspace: { gap: 20, flexDirection: compact ? `column` : `row`, alignItems: `stretch` },
  sidebar: { gap: 22, width: compact ? `100%` : 180, padding: compact ? 10 : 18, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper },
  sidebarProfile: { gap: 12, paddingBottom: 20, borderBottomWidth: 1, borderBottomColor: palette.line },
  sidebarNote: { gap: 12, padding: 14, marginTop: `auto`, borderRadius: 10, backgroundColor: palette.subtle },
  navigation: { gap: 8, flexDirection: compact ? `row` : `column`, flexWrap: compact ? `wrap` : `nowrap` },
  navigationItem: { gap: 10, minWidth: 0, padding: 11, borderRadius: 8, flexDirection: `row`, alignItems: `center`, ...(compact ? { flexGrow: 1, flexBasis: 70 } : {}) },
  navigationSelected: { backgroundColor: palette.subtle },
  navigationLine: { flex: 1, height: 8 },
  smallAvatar: { width: 46, height: 46, borderRadius: 16 },
  name: { width: `76%`, height: 12 },
  shortLine: { width: `48%` },
  longLine: { width: `84%` },
  titleLine: { width: `45%`, height: 12 },
  content: { gap: 16, minWidth: 0, ...(!compact ? { flex: 1 } : {}) },
  summary: { gap: compact ? 8 : 14, flexDirection: `row` },
  summaryCard: { gap: 12, flex: 1, minWidth: 0, padding: compact ? 13 : 18, borderWidth: 1, borderRadius: 12, borderColor: palette.line, backgroundColor: palette.paper },
  summaryMark: { width: 9, height: 9, borderRadius: 3, backgroundColor: palette.accent, opacity: .6 },
  summaryValue: { width: `58%`, height: compact ? 20 : 24 },
  panelHeading: { gap: 10, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  panels: { gap: 16, flexDirection: roomy ? `row` : `column`, alignItems: `stretch` },
  form: { gap: 18, minWidth: 0, padding: compact ? 18 : 24, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper, ...(roomy ? { flex: 1 } : {}) },
  fields: { gap: 16, flexDirection: `row`, flexWrap: `wrap` },
  field: { gap: 10, flexGrow: 1, flexBasis: 180 },
  fullField: { flexBasis: `100%` },
  fieldLabel: { width: `28%`, height: 8 },
  input: { width: `100%`, height: 40, borderRadius: 8 },
  textarea: { width: `100%`, height: 76, borderRadius: 8 },
  preference: { gap: 16, paddingVertical: 4, alignItems: `center`, flexDirection: `row` },
  preferenceCopy: { gap: 9, flex: 1, minWidth: 0 },
  toggle: { width: 36, height: 20, borderRadius: 10 },
  formFooter: { gap: 16, paddingTop: 4, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  save: { width: 120, height: 38, borderRadius: 8, backgroundColor: palette.subtle },
  status: { width: `26%`, height: 8 },
  details: { gap: 16, width: roomy ? 260 : `100%`, flexDirection: roomy ? `column` : `row`, flexWrap: roomy ? `nowrap` : `wrap` },
  detailCard: { gap: 17, minWidth: 0, padding: 20, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper, ...(!roomy ? { flexGrow: 1, flexBasis: 180 } : {}) },
  detailField: { gap: 10, paddingVertical: 6, borderBottomWidth: 1, paddingBottom: 15, borderBottomColor: palette.line },
  accentCard: { backgroundColor: palette.subtle },
  connectionMarks: { gap: 8, paddingTop: 2, flexDirection: `row` },
  connectionMark: { width: 26, height: 26, borderRadius: 8 },
});
