import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  page: { gap: 28, width: `100%`, maxWidth: 1120, alignSelf: `center`, paddingTop: 52, paddingBottom: 44, paddingHorizontal: 24 },
  compactPage: { gap: 22, paddingTop: 30, paddingHorizontal: 20 },
  intro: { gap: 14 },
  eyebrow: { gap: 7, flexDirection: `row`, alignItems: `center` },
  eyebrowText: { fontSize: 10, letterSpacing: 1.5, color: palette.accent, fontFamily: `DMSans_700Bold` },
  title: { fontSize: 48, lineHeight: 54, color: palette.ink, fontFamily: `InstrumentSerif_400Regular` },
  compactTitle: { fontSize: 39, lineHeight: 45 },
  description: { maxWidth: 560, fontSize: 13, lineHeight: 22, color: palette.muted, fontFamily: `DMSans_400Regular` },
  form: { gap: 12, padding: 22, borderWidth: 1, borderRadius: 14, borderColor: palette.line, backgroundColor: palette.paper },
  inputLabel: { fontSize: 11, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  formRow: { gap: 12, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  inputWrap: { flex: 1, gap: 12, minWidth: 220, height: 52, borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, flexDirection: `row`, alignItems: `center`, borderColor: palette.line, backgroundColor: palette.input },
  input: { flex: 1, minWidth: 0, padding: 0, height: 50, fontSize: 14, color: palette.ink, fontFamily: `DMSans_500Medium` },
  clearButton: { padding: 4 },
  searchButton: { gap: 8, minHeight: 52, paddingHorizontal: 22, borderRadius: 8, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.accent },
  searchButtonText: { fontSize: 12, color: palette.contrast, fontFamily: `DMSans_600SemiBold` },
  disabled: { opacity: .55 },
  formFooter: { gap: 12, flexDirection: `row`, flexWrap: `wrap`, justifyContent: `space-between`, alignItems: `center` },
  formHint: { flexShrink: 1, fontSize: 10, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  textLink: { gap: 5, paddingVertical: 3, flexDirection: `row`, alignItems: `center` },
  textLinkText: { fontSize: 10, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  errorPanel: { padding: 14, borderRadius: 8, backgroundColor: palette.dangerBackground },
  errorText: { fontSize: 12, lineHeight: 19, color: palette.danger, fontFamily: `DMSans_500Medium` },
  prompt: { gap: 16, padding: 22, borderWidth: 1, borderRadius: 12, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center`, borderColor: palette.line, backgroundColor: palette.paper },
  promptCopy: { flex: 1, gap: 5, minWidth: 180 },
  promptTitle: { fontSize: 13, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  promptDescription: { fontSize: 11, lineHeight: 19, color: palette.muted, fontFamily: `DMSans_400Regular` },
  secondaryButton: { gap: 7, paddingVertical: 11, paddingHorizontal: 14, borderWidth: 1, borderRadius: 7, flexDirection: `row`, alignItems: `center`, borderColor: palette.line },
  secondaryButtonText: { fontSize: 11, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  resultsSection: { gap: 17 },
  resultsHeading: { gap: 10, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center`, justifyContent: `space-between` },
  resultsTitle: { fontSize: 14, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  resultsCount: { fontSize: 10, color: palette.muted, fontFamily: `DMSans_500Medium` },
  resultsGrid: { gap: 16, flexWrap: `wrap`, flexDirection: `row` },
  resultCard: { flex: 1, gap: 20, minWidth: 250, maxWidth: `100%`, flexBasis: 280, padding: 20, borderWidth: 1, borderRadius: 12, borderColor: palette.line, backgroundColor: palette.paper },
  resultHeading: { gap: 12, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center`, justifyContent: `space-between` },
  registrar: { gap: 7, flexDirection: `row`, alignItems: `center` },
  registrarName: { fontSize: 11, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  actionsCell: { minHeight: 18 },
  rowStatus: { gap: 4, flexDirection: `row`, alignItems: `center` },
  statusDotWrap: { width: 12, alignItems: `center` },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusText: { fontSize: 10, fontFamily: `DMSans_500Medium` },
  resultDomain: { fontSize: 19, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  prices: { gap: 14, paddingVertical: 17, borderTopWidth: 1, borderBottomWidth: 1, flexDirection: `row`, borderTopColor: palette.line, borderBottomColor: palette.line },
  price: { flex: 1, gap: 7, minWidth: 0 },
  priceLabel: { fontSize: 10, color: palette.muted, fontFamily: `DMSans_400Regular` },
  priceAmount: { fontSize: 17, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  currencyNote: { fontSize: 9, lineHeight: 16, color: palette.warning, fontFamily: `DMSans_500Medium` },
  priceTerm: { fontSize: 10, color: palette.muted, fontFamily: `DMSans_400Regular` },
  resultError: { fontSize: 11, lineHeight: 18, color: palette.danger, fontFamily: `DMSans_500Medium` },
  resultNote: { fontSize: 10, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  purchaseLink: { gap: 7, marginTop: `auto`, paddingTop: 3, flexDirection: `row`, alignItems: `center`, alignSelf: `flex-start` },
  purchaseText: { fontSize: 11, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  disclaimer: { fontSize: 10, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  readyNote: { gap: 8, flexDirection: `row`, alignItems: `center` },
  readyCopy: { flex: 1, fontSize: 10, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  skeleton: { borderRadius: 4, backgroundColor: palette.skeleton },
  skeletonHeading: { width: `44%`, height: 16 },
  skeletonDomain: { width: `76%`, height: 23 },
  skeletonLabel: { width: `60%`, height: 12 },
  skeletonAmount: { width: `80%`, height: 22, marginTop: 4 },
  skeletonLink: { width: `42%`, height: 14 },
});
