import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  fullSection: { paddingTop: 48 },
  section: { gap: 20, padding: 24, paddingTop: 28 },
  heading: { gap: 14 },
  headingCopy: { gap: 7 },
  syncButton: { minHeight: 44, flexShrink: 1 },
  headingActions: { gap: 8, minWidth: 0, maxWidth: `100%`, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  syncStatus: { gap: 8, flexDirection: `row`, alignItems: `center` },
  manualSyncMessage: { color: palette.muted, fontSize: 12, lineHeight: 18, fontFamily: `DMSans_400Regular` },
  eyebrow: { color: palette.accent, fontSize: 9, letterSpacing: 1.5, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: 29, lineHeight: 34, letterSpacing: -.8, fontFamily: `DMSans_700Bold` },
  description: { color: palette.muted, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  headingBottom: { gap: 15, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  counts: { gap: 4, flex: 1, minWidth: 150 },
  addButton: { flexShrink: 0 },
  countSummary: { gap: 8, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  registrarCount: { gap: 4, maxWidth: `100%`, flexDirection: `row`, alignItems: `center` },
  registrarCountLabel: { flexShrink: 1, color: palette.muted, fontSize: 10, fontFamily: `DMSans_400Regular` },
  registrarCountValue: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_600SemiBold` },
  countText: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  attentionText: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_500Medium` },
  primaryButton: { gap: 8, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 6, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.strong },
  primaryButtonText: { color: `#ffffff`, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  secondaryButton: { gap: 7, paddingVertical: 11, paddingHorizontal: 13, borderWidth: 1, borderRadius: 6, borderColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.paper },
  secondaryButtonText: { color: palette.ink, fontSize: 11, fontFamily: `DMSans_600SemiBold` },
  disabled: { opacity: .45 },
  notice: { gap: 10, padding: 14, borderRadius: 6, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.successBackground },
  noticeText: { flex: 1, color: palette.success, fontSize: 11, lineHeight: 18, fontFamily: `DMSans_500Medium` },
  noticeDismiss: { padding: 4 },
  error: { gap: 7, padding: 14, borderRadius: 6, backgroundColor: palette.dangerBackground },
  errorText: { color: palette.danger, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_500Medium` },
  tools: { gap: 12, padding: 14, borderWidth: 1, borderRadius: 8, borderColor: palette.line, backgroundColor: palette.paper },
  searchRow: { gap: 10, flexDirection: `row`, alignItems: `center` },
  search: { gap: 9, flex: 1, paddingHorizontal: 13, minHeight: 45, borderWidth: 1, borderRadius: 6, borderColor: palette.line, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.input },
  searchInput: { flex: 1, paddingVertical: 11, color: palette.ink, fontSize: 12, fontFamily: `DMSans_400Regular` },
  sortButton: { width: 44, height: 45, borderWidth: 1, borderRadius: 6, borderColor: palette.line, alignItems: `center`, justifyContent: `center` },
  registrarScroll: { flexGrow: 0 },
  registrarList: { gap: 7, paddingVertical: 2 },
  registrarButton: { paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderRadius: 6, borderColor: palette.line },
  registrarButtonActive: { borderColor: palette.accent, backgroundColor: palette.subtle },
  registrarText: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_600SemiBold` },
  registrarTextActive: { color: palette.accent },
  records: { gap: 10 },
  empty: { gap: 12, padding: 30, borderWidth: 1, borderRadius: 8, borderColor: palette.line, alignItems: `center`, backgroundColor: palette.paper },
  emptyTitle: { color: palette.ink, fontSize: 18, fontFamily: `DMSans_600SemiBold` },
  emptyDescription: { color: palette.muted, fontSize: 12, lineHeight: 20, textAlign: `center`, fontFamily: `DMSans_400Regular` },
  bottom: { gap: 8, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  bottomText: { flex: 1, minWidth: 0, color: palette.muted, fontSize: 10, fontFamily: `DMSans_400Regular` },
  textButton: { gap: 5, paddingVertical: 6, flexDirection: `row`, alignItems: `center` },
  textButtonText: { color: palette.accent, fontSize: 10, fontFamily: `DMSans_500Medium` },
  overlay: { flex: 1, padding: 18, backgroundColor: palette.overlay },
  keyboard: { flex: 1, alignItems: `center`, justifyContent: `center` },
  modal: { width: `100%`, maxWidth: 540, maxHeight: `100%`, borderRadius: 10, flexShrink: 1, backgroundColor: palette.paper },
  modalHeader: { gap: 16, padding: 22, paddingBottom: 18, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between`, borderBottomWidth: 1, borderBottomColor: palette.line },
  modalHeading: { gap: 6, flex: 1, minWidth: 0 },
  modalEyebrow: { color: palette.accent, fontSize: 9, letterSpacing: 1.5, fontFamily: `DMSans_600SemiBold` },
  modalTitle: { flexShrink: 1, color: palette.ink, fontSize: 25, letterSpacing: -.5, fontFamily: `DMSans_700Bold` },
  modalTitleRow: { gap: 8, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  modalRegistrarInfo: { gap: 6, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center` },
  modalRegistrar: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_500Medium` },
  modalClose: { padding: 8, borderRadius: 6, backgroundColor: palette.input },
  formScroll: { flexShrink: 1 },
  form: { gap: 18, padding: 22 },
  field: { gap: 8 },
  pairedField: { flex: 1, minWidth: 0 },
  fieldReadonly: { opacity: .65 },
  fieldPair: { gap: 14, flexDirection: `row`, alignItems: `flex-start` },
  fieldLabel: { color: palette.ink, fontSize: 11, fontFamily: `DMSans_600SemiBold` },
  fieldInput: { minHeight: 45, padding: 13, borderWidth: 1, borderRadius: 6, borderColor: palette.line, color: palette.ink, backgroundColor: palette.input, fontSize: 13, fontFamily: `DMSans_400Regular` },
  priceInput: { paddingLeft: 30 },
  priceControl: { position: `relative` },
  priceCurrency: { fontSize: 13, color: palette.muted, fontFamily: `DMSans_400Regular` },
  pricePrefix: { top: 0, left: 13, bottom: 0, zIndex: 1, position: `absolute`, pointerEvents: `none`, justifyContent: `center` },
  siteIconRow: { gap: 12, flexDirection: `row`, alignItems: `center` },
  siteIconInput: { flex: 1, minWidth: 0 },
  siteIconPreview: { width: 48, height: 48, borderWidth: 1, borderRadius: 8, borderColor: palette.line, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.input },
  siteIconImage: { width: 30, height: 30, resizeMode: `contain` },
  descriptionInput: { minHeight: 88, textAlignVertical: `top` },
  fieldHint: { color: palette.muted, fontSize: 10, lineHeight: 16, fontFamily: `DMSans_400Regular` },
  registrarChoices: { gap: 7, flexWrap: `wrap`, flexDirection: `row` },
  toggle: { gap: 12, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  toggleCopy: { gap: 4, flex: 1 },
  modalFooter: { gap: 12, padding: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: palette.line },
  modalFootnote: { color: palette.muted, fontSize: 10, lineHeight: 17, textAlign: `center`, fontFamily: `DMSans_400Regular` },
});
