import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  section: { gap: 20, padding: 24, paddingTop: 32 },
  heading: { gap: 14 },
  headingCopy: { gap: 7 },
  eyebrow: { color: `#138b8b`, fontSize: 10, letterSpacing: 2, fontFamily: `DMSans_600SemiBold` },
  title: { color: `#133b50`, fontSize: 36, lineHeight: 41, fontFamily: `InstrumentSerif_400Regular` },
  description: { color: `#7e8981`, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  headingBottom: { gap: 15, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  counts: { gap: 4 },
  countText: { color: `#133b50`, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  attentionText: { color: `#8a938d`, fontSize: 10, fontFamily: `DMSans_400Regular` },
  primaryButton: { gap: 8, paddingVertical: 12, paddingHorizontal: 16, borderRadius: 10, flexDirection: `row`, alignItems: `center`, justifyContent: `center`, backgroundColor: `#133b50` },
  primaryButtonText: { color: `#fffefa`, fontSize: 12, fontFamily: `DMSans_500Medium` },
  secondaryButton: { gap: 7, paddingVertical: 11, paddingHorizontal: 13, borderWidth: 1, borderRadius: 9, borderColor: `#dce3d9`, flexDirection: `row`, alignItems: `center`, justifyContent: `center` },
  secondaryButtonText: { color: `#61716f`, fontSize: 11, fontFamily: `DMSans_500Medium` },
  disabled: { opacity: .45 },
  notice: { gap: 10, padding: 14, borderRadius: 10, flexDirection: `row`, alignItems: `center`, backgroundColor: `#e6efe7` },
  noticeText: { flex: 1, color: `#248477`, fontSize: 11, lineHeight: 18, fontFamily: `DMSans_500Medium` },
  noticeDismiss: { padding: 4 },
  error: { gap: 7, padding: 14, borderRadius: 10, backgroundColor: `#f8e9e1` },
  errorText: { color: `#ad5653`, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_500Medium` },
  tools: { gap: 12 },
  searchRow: { gap: 10, flexDirection: `row`, alignItems: `center` },
  search: { gap: 9, flex: 1, paddingHorizontal: 13, minHeight: 45, borderWidth: 1, borderRadius: 10, borderColor: `#dce3d9`, flexDirection: `row`, alignItems: `center`, backgroundColor: `#fffefa` },
  searchInput: { flex: 1, paddingVertical: 11, color: `#133b50`, fontSize: 12, fontFamily: `DMSans_400Regular` },
  sortButton: { width: 44, height: 45, borderWidth: 1, borderRadius: 10, borderColor: `#dce3d9`, alignItems: `center`, justifyContent: `center` },
  registrarScroll: { flexGrow: 0 },
  registrarList: { gap: 7, paddingVertical: 2 },
  registrarButton: { paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderRadius: 20, borderColor: `#e0e4dc` },
  registrarButtonActive: { borderColor: `#138b8b`, backgroundColor: `#e8f1eb` },
  registrarText: { color: `#7e8981`, fontSize: 10, fontFamily: `DMSans_500Medium` },
  registrarTextActive: { color: `#138b8b` },
  csvActions: { gap: 9, flexDirection: `row`, alignItems: `center` },
  csvHint: { color: `#8a938d`, fontSize: 10, lineHeight: 17, fontFamily: `DMSans_400Regular` },
  records: { gap: 12 },
  empty: { gap: 12, padding: 30, borderWidth: 1, borderRadius: 16, borderColor: `#dce3d9`, alignItems: `center`, backgroundColor: `#fffefa` },
  emptyTitle: { color: `#133b50`, fontSize: 18, fontFamily: `DMSans_600SemiBold` },
  emptyDescription: { color: `#7e8981`, fontSize: 12, lineHeight: 20, textAlign: `center`, fontFamily: `DMSans_400Regular` },
  bottom: { gap: 14, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  bottomText: { color: `#8a938d`, fontSize: 10, fontFamily: `DMSans_400Regular` },
  textButton: { gap: 5, paddingVertical: 6, flexDirection: `row`, alignItems: `center` },
  textButtonText: { color: `#138b8b`, fontSize: 10, fontFamily: `DMSans_500Medium` },
  overlay: { flex: 1, padding: 18, backgroundColor: `rgba(19, 59, 80, .3)` },
  keyboard: { flex: 1, alignItems: `center`, justifyContent: `center` },
  modal: { width: `100%`, maxWidth: 540, maxHeight: `100%`, borderRadius: 20, flexShrink: 1, backgroundColor: `#f7f6f2` },
  modalHeader: { gap: 16, padding: 22, paddingBottom: 18, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between`, borderBottomWidth: 1, borderBottomColor: `#e0e4dc` },
  modalHeading: { gap: 6, flex: 1 },
  modalEyebrow: { color: `#138b8b`, fontSize: 9, letterSpacing: 1.5, fontFamily: `DMSans_600SemiBold` },
  modalTitle: { color: `#133b50`, fontSize: 29, fontFamily: `InstrumentSerif_400Regular` },
  modalClose: { padding: 8, borderRadius: 20, backgroundColor: `#e9ede5` },
  formScroll: { flexShrink: 1 },
  form: { gap: 18, padding: 22 },
  field: { gap: 8 },
  fieldLabel: { color: `#61716f`, fontSize: 11, fontFamily: `DMSans_500Medium` },
  fieldInput: { minHeight: 45, padding: 13, borderWidth: 1, borderRadius: 10, borderColor: `#dce3d9`, color: `#133b50`, backgroundColor: `#fffefa`, fontSize: 13, fontFamily: `DMSans_400Regular` },
  notesInput: { minHeight: 88, textAlignVertical: `top` },
  fieldHint: { color: `#8a938d`, fontSize: 10, lineHeight: 16, fontFamily: `DMSans_400Regular` },
  registrarChoices: { gap: 7, flexWrap: `wrap`, flexDirection: `row` },
  toggle: { gap: 12, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  toggleCopy: { gap: 4, flex: 1 },
  modalFooter: { gap: 12, padding: 22, paddingTop: 18, borderTopWidth: 1, borderTopColor: `#e0e4dc` },
  modalFootnote: { color: `#8a938d`, fontSize: 10, lineHeight: 17, textAlign: `center`, fontFamily: `DMSans_400Regular` },
});
