import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  body: { gap: 8 },
  roomyGrid: { flexWrap: `wrap`, flexDirection: `row` },
  roomyButton: { flexGrow: 1, flexBasis: 180 },
  headingText: { flex: 1 },
  buttonText: { flex: 1 },
  root: { gap: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: palette.line },
  roomyRoot: { flex: 1, minWidth: 0, paddingTop: 0, paddingLeft: 16, borderTopWidth: 0, borderLeftWidth: 1, borderLeftColor: palette.line },
  disabled: { opacity: .55 },
  details: { gap: 6 },
  sections: { gap: 12 },
  wideDetails: { flexGrow: 1, flexBasis: `47%`, minWidth: 0 },
  extraWideDetails: { flexGrow: 1, flexBasis: `30%`, minWidth: 0 },
  wideSections: { flexWrap: `wrap`, flexDirection: `row`, alignItems: `stretch` },
  detailCard: { padding: 14, borderWidth: 1, borderRadius: 8, borderColor: palette.line, backgroundColor: palette.subtle },
  text: { fontSize: 12, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  copy: { fontSize: 11, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  heading: { gap: 8, minHeight: 36, flexDirection: `row`, alignItems: `center` },
  button: { gap: 8, minHeight: 40, padding: 10, borderWidth: 1, borderRadius: 6, borderColor: palette.line, flexDirection: `row`, alignItems: `center` },
  dangerText: { color: palette.danger },
  overlay: { flex: 1, paddingHorizontal: 16, overflow: `hidden`, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.overlay },
  dialogScroll: { minHeight: 0, flexGrow: 0, flexShrink: 1 },
  dialogContent: { gap: 12, padding: 18 },
  compactDialogHeader: { padding: 12 },
  compactDialogActions: { padding: 12 },
  dialogHeader: { padding: 16, flexShrink: 0, borderBottomWidth: 1, borderBottomColor: palette.line },
  dialog: { width: `100%`, maxWidth: 1440, minHeight: 0, flexShrink: 1, overflow: `hidden`, borderWidth: 1, borderRadius: 12, borderColor: palette.line, backgroundColor: palette.paper },
  title: { flex: 1, fontSize: 19, color: palette.ink, fontFamily: `DMSans_700Bold` },
  close: { width: 36, height: 36, alignItems: `center`, justifyContent: `center` },
  dialogCopy: { fontSize: 12, lineHeight: 19, color: palette.muted, fontFamily: `DMSans_400Regular` },
  detailsTitle: { fontSize: 13, lineHeight: 18, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  error: { fontSize: 12, lineHeight: 18, color: palette.danger, fontFamily: `DMSans_400Regular` },
  actions: { gap: 10, padding: 12, flexShrink: 0, borderTopWidth: 1, borderTopColor: palette.line, flexWrap: `wrap`, flexDirection: `row`, justifyContent: `flex-end` },
  confirm: { backgroundColor: palette.dangerBackground, borderColor: palette.danger },
});
