import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette, compact: boolean, width: number, height?: number) => {
  const condensed = !compact && height !== undefined && height < 700;
  return StyleSheet.create({
  page: { gap: compact ? 28 : 40, width: `100%`, maxWidth: 1400, minHeight: compact ? undefined : height, padding: compact ? 18 : 32, paddingVertical: condensed ? 12 : compact ? 18 : 32, alignSelf: `center`, alignItems: compact ? `stretch` : `center`, flexDirection: compact ? `column` : `row` },
  intro: { gap: condensed ? 12 : 18, flex: compact ? undefined : 1, minWidth: 0, justifyContent: `center` },
  eyebrowRow: { gap: 8, alignItems: `center`, flexDirection: `row` },
  eyebrow: { color: palette.accent, fontSize: 10, letterSpacing: 1.6, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: compact ? Math.min(48, Math.max(32, width * .09)) : condensed ? 42 : 52, lineHeight: compact ? Math.min(52, Math.max(36, width * .1)) : condensed ? 46 : 56, letterSpacing: -1.8, fontFamily: `DMSans_700Bold` },
  titleAccent: { color: palette.accent, fontStyle: `italic` },
  description: { color: palette.muted, maxWidth: 470, fontSize: 14, lineHeight: 23, fontFamily: `DMSans_400Regular` },
  illustration: { height: condensed ? 128 : 176, width: `100%`, overflow: `hidden`, position: `relative`, borderRadius: 18, backgroundColor: palette.subtle },
  orbit: { top: 19, left: `14%`, width: `70%`, height: 133, borderWidth: 1, borderRadius: 100, borderStyle: `dashed`, borderColor: palette.line, transform: [{ rotate: `-14deg` }], position: `absolute` },
  orbitDot: { top: 15, left: `43%`, width: 7, height: 7, borderRadius: 4, position: `absolute`, backgroundColor: palette.accent },
  domainCard: { top: 30, left: `6%`, gap: 7, width: 170, padding: 17, borderWidth: 1, borderRadius: 13, borderColor: palette.line, backgroundColor: palette.paper, transform: [{ rotate: `-7deg` }], position: `absolute` },
  domainName: { color: palette.ink, fontSize: 14, fontFamily: `DMSans_700Bold` },
  domainNote: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_400Regular` },
  messageCard: { gap: 9, right: `4%`, bottom: 22, width: 183, padding: 16, borderRadius: 12, backgroundColor: palette.accent, transform: [{ rotate: `5deg` }], position: `absolute` },
  messageCopy: { color: palette.contrast, fontSize: 12, fontFamily: `DMSans_700Bold` },
  messageLine: { width: `62%`, height: 4, opacity: .4, borderRadius: 3, backgroundColor: palette.contrast },
  spark: { top: 21, right: `18%`, width: 34, height: 34, borderWidth: 1, borderRadius: 17, alignItems: `center`, justifyContent: `center`, borderColor: palette.line, backgroundColor: palette.paper, position: `absolute` },
  topics: { gap: 20, flexDirection: `row` },
  topic: { gap: 9, flex: 1, minWidth: 0 },
  topicSymbol: { width: 34, height: 34, borderRadius: 9, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  topicTitle: { color: palette.ink, fontSize: 13, fontFamily: `DMSans_700Bold` },
  topicCopy: { color: palette.muted, fontSize: 12, lineHeight: 19, fontFamily: `DMSans_400Regular` },
  helpLinks: { gap: 12, paddingTop: condensed ? 8 : 14, borderTopWidth: 1, flexDirection: `row`, flexWrap: `wrap`, borderTopColor: palette.line },
  helpLink: { gap: 7, minHeight: 44, alignItems: `center`, flexDirection: `row` },
  helpLinkText: { color: palette.accent, fontSize: 11, fontFamily: `DMSans_500Medium` },
  panel: { gap: condensed ? 16 : 22, width: compact ? `100%` : width >= 1100 ? 500 : 430, justifyContent: `center` },
  formHeading: { gap: condensed ? 6 : 10 },
  formSymbol: { width: 42, height: 42, borderRadius: 12, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  formTitle: { color: palette.ink, fontSize: 30, lineHeight: 36, letterSpacing: -1.1, fontFamily: `DMSans_700Bold` },
  formDescription: { color: palette.muted, fontSize: 13, lineHeight: 21, fontFamily: `DMSans_400Regular` },
  form: { gap: condensed ? 12 : 15 },
  fields: { gap: condensed ? 12 : 16, flexWrap: `wrap`, flexDirection: `row` },
  field: { gap: condensed ? 5 : 7, minWidth: 0, width: `100%` },
  halfField: { width: undefined, flexGrow: 1, flexBasis: `45%` },
  label: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  input: { color: palette.ink, minHeight: condensed ? 44 : 48, paddingVertical: condensed ? 10 : 12, paddingHorizontal: 13, borderWidth: 1, borderRadius: 8, fontSize: 16, borderColor: palette.line, backgroundColor: palette.input, fontFamily: `DMSans_400Regular` },
  messageInput: { height: condensed ? 96 : 140, lineHeight: 23, textAlignVertical: `top` },
  invalidInput: { borderColor: palette.danger },
  errorText: { color: palette.danger, fontSize: 11, lineHeight: 17, fontFamily: `DMSans_400Regular` },
  messageHint: { gap: 12, flexDirection: `row`, justifyContent: `space-between` },
  messageSafety: { flex: 1, color: palette.muted, fontSize: 10, lineHeight: 16, fontFamily: `DMSans_400Regular` },
  messageCount: { color: palette.muted, fontSize: 10, lineHeight: 16, fontFamily: `DMSans_400Regular` },
  submit: { gap: 10, minHeight: condensed ? 44 : 48, width: `100%`, paddingHorizontal: 16, paddingVertical: condensed ? 10 : 12, borderRadius: 9, alignItems: `center`, flexDirection: `row`, backgroundColor: palette.accent },
  submitText: { flex: 1, color: palette.contrast, fontSize: 13, fontFamily: `DMSans_700Bold` },
  disabled: { opacity: .55 },
  privacyNote: { color: palette.muted, fontSize: 10, lineHeight: 17, textAlign: `center`, fontFamily: `DMSans_400Regular` },
  privacyLink: { color: palette.accent, textDecorationLine: `underline` },
  success: { gap: condensed ? 16 : 20, minHeight: condensed ? 300 : compact ? 340 : 430, alignItems: `flex-start`, justifyContent: `center` },
  successSymbol: { width: 64, height: 64, borderRadius: 32, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.successBackground },
  successReference: { color: palette.muted, paddingVertical: 7, paddingHorizontal: 10, borderWidth: 1, borderRadius: 6, fontSize: 11, borderColor: palette.line, backgroundColor: palette.input, fontFamily: `DMSans_400Regular` },
  });
};
