import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  page: { width: `100%`, maxWidth: 510, alignSelf: `center`, padding: 24, paddingVertical: 52 },
  panel: { gap: 24, padding: 28, borderWidth: 1, borderRadius: 18, borderColor: palette.line, backgroundColor: palette.paper },
  heading: { gap: 12 },
  eyebrow: { color: palette.accent, fontSize: 10, letterSpacing: 2, fontFamily: `DMSans_600SemiBold` },
  title: { color: palette.ink, fontSize: 42, lineHeight: 46, fontFamily: `InstrumentSerif_400Regular` },
  description: { color: palette.muted, fontSize: 13, lineHeight: 21, fontFamily: `DMSans_400Regular` },
  form: { gap: 18 },
  field: { gap: 8 },
  label: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  inputFrame: { gap: 11, minHeight: 48, paddingHorizontal: 13, borderWidth: 1, borderRadius: 9, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.input },
  input: { flex: 1, paddingVertical: 12, color: palette.ink, fontSize: 14, fontFamily: `DMSans_400Regular` },
  toggle: { padding: 5, borderRadius: 5 },
  help: { color: palette.muted, fontSize: 11, lineHeight: 17, fontFamily: `DMSans_400Regular` },
  submit: { gap: 9, minHeight: 48, paddingHorizontal: 18, borderRadius: 9, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, backgroundColor: palette.accent },
  submitText: { color: palette.contrast, fontSize: 13, fontFamily: `DMSans_600SemiBold` },
  disabled: { opacity: 0.5 },
  switchRow: { gap: 5, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, flexWrap: `wrap` },
  switchCopy: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_400Regular` },
  switchLink: { gap: 5, padding: 5, flexDirection: `row`, alignItems: `center` },
  switchText: { color: palette.accent, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  localNote: { gap: 9, paddingTop: 18, borderTopWidth: 1, flexDirection: `row`, borderTopColor: palette.line },
  localCopy: { flex: 1, color: palette.muted, fontSize: 11, lineHeight: 18, fontFamily: `DMSans_400Regular` },
  feedback: { padding: 12, borderRadius: 8, backgroundColor: palette.dangerBackground },
  errorText: { color: palette.danger, fontSize: 12, lineHeight: 18, fontFamily: `DMSans_500Medium` },
  notice: { padding: 12, borderRadius: 8, backgroundColor: palette.successBackground },
  noticeText: { color: palette.success, fontSize: 12, lineHeight: 18, fontFamily: `DMSans_500Medium` },
  skeletonTitle: { height: 36, width: `65%`, borderRadius: 7, backgroundColor: palette.skeleton },
  skeletonCopy: { height: 15, width: `90%`, borderRadius: 5, backgroundColor: palette.skeleton },
  skeletonField: { height: 48, borderRadius: 9, backgroundColor: palette.skeleton },
});
