import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette, compact = false, condensed = false, height?: number, landscape = false) => StyleSheet.create({
  page: {
    gap: compact ? 0 : 24,
    height,
    width: `100%`,
    maxWidth: 1200,
    alignSelf: `center`,
    padding: compact ? 0 : 20,
    paddingVertical: compact ? 0 : 24,
    alignItems: `stretch`,
    flexDirection: compact ? `column` : `row`,
  },
  story: {
    gap: condensed ? 20 : 28,
    flex: compact ? undefined : 1,
    padding: condensed ? 24 : 28,
    borderWidth: compact ? 0 : 1,
    borderRadius: 22,
    borderColor: palette.line,
    backgroundColor: compact ? `transparent` : palette.subtle,
  },
  logo: { width: 194, height: 44 },
  storyHeading: { gap: condensed ? 12 : 18 },
  storyTitle: { color: palette.ink, fontSize: condensed ? 36 : 46, lineHeight: condensed ? 40 : 50, letterSpacing: -1.8, fontFamily: `DMSans_700Bold` },
  storyAccent: { color: palette.accent },
  storyDescription: { color: palette.muted, fontSize: compact ? 15 : 16, lineHeight: 26, fontFamily: `DMSans_400Regular` },
  preview: { gap: 10, padding: 16, borderWidth: 1, borderRadius: 16, borderColor: palette.line, backgroundColor: palette.paper },
  previewHeading: { gap: 9, marginBottom: 6, alignItems: `center`, flexDirection: `row` },
  previewLabel: { color: palette.muted, fontSize: 10, letterSpacing: 1.4, fontFamily: `DMSans_700Bold` },
  previewRecord: { gap: 12, minHeight: 48, padding: 8, borderWidth: 1, borderRadius: 10, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.input },
  previewSymbol: { width: 34, height: 34, borderRadius: 9, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  previewName: { flex: 1, color: palette.ink, fontSize: 14, fontFamily: `DMSans_600SemiBold` },
  previewLine: { width: 32, height: 5, borderRadius: 3, backgroundColor: palette.skeleton },
  panel: { gap: condensed ? 10 : 16, flex: 1, minWidth: 0, padding: condensed ? 16 : 24, borderWidth: 1, borderRadius: 16, justifyContent: `center`, borderColor: palette.line, backgroundColor: palette.paper },
  modes: { gap: 4, padding: condensed ? 0 : 4, borderWidth: 1, borderRadius: 10, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.input },
  mode: { gap: 7, flex: 1, minHeight: 44, borderWidth: 1, borderRadius: 8, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, borderColor: `transparent` },
  modeText: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  modeSelected: { borderColor: palette.line, backgroundColor: palette.paper },
  modeTextSelected: { color: palette.ink },
  heading: { gap: 8 },
  eyebrow: { color: palette.accent, fontSize: 10, letterSpacing: 1.6, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: compact ? 28 : 34, lineHeight: compact ? 32 : 40, letterSpacing: -1.2, fontFamily: `DMSans_700Bold` },
  description: { color: palette.muted, fontSize: 13, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  form: { gap: condensed ? 10 : 12, flexDirection: landscape ? `row` : `column`, alignItems: landscape ? `flex-end` : `stretch` },
  field: { gap: condensed ? 5 : 6, flex: landscape ? 1 : undefined, minWidth: 0 },
  label: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  inputFrame: { gap: 12, minHeight: condensed ? 44 : 48, paddingHorizontal: 14, borderWidth: 1, borderRadius: 8, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.input },
  input: { flex: 1, minWidth: 0, paddingVertical: condensed ? 9 : 12, color: palette.ink, fontSize: 16, fontFamily: `DMSans_400Regular` },
  toggle: { width: 44, height: 44, marginRight: -8, borderRadius: 8, alignItems: `center`, justifyContent: `center` },
  submit: { gap: 10, minHeight: condensed ? 44 : 48, paddingHorizontal: 20, borderRadius: 8, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, backgroundColor: palette.accent },
  submitText: { color: palette.contrast, fontSize: 15, fontFamily: `DMSans_700Bold` },
  disabled: { opacity: 0.5 },
  localNote: { gap: 9, paddingTop: 12, borderTopWidth: 1, flexDirection: `row`, alignItems: `center`, borderTopColor: palette.line },
  localCopy: { flex: 1, color: palette.muted, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  loading: { gap: 16 },
  signedIn: { gap: 20, justifyContent: `center` },
  skeletonTitle: { height: 42, width: `75%`, borderRadius: 8, backgroundColor: palette.skeleton },
  skeletonCopy: { height: 18, width: `90%`, borderRadius: 5, backgroundColor: palette.skeleton },
  skeletonField: { height: condensed ? 44 : 48, borderRadius: 8, backgroundColor: palette.skeleton },
});
