import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette, compact = false, condensed = false, height?: number, width = 1600) => StyleSheet.create({
  page: {
    gap: compact ? 16 : 32,
    width: `100%`,
    maxWidth: compact ? 1600 : undefined,
    minHeight: compact ? undefined : height,
    alignSelf: `center`,
    padding: compact ? 16 : 24,
    paddingVertical: compact ? 8 : 24,
    paddingHorizontal: compact ? 16 : 24 + Math.max(0, (width - 1600) / 2),
    backgroundColor: compact ? undefined : palette.paper,
    alignItems: `stretch`,
    flexDirection: compact ? `column` : `row`,
  },
  panel: { gap: condensed ? 10 : 18, width: compact ? `100%` : 440, minWidth: 0, flexShrink: 0, padding: condensed ? 20 : 30, borderWidth: compact ? 1 : 0, borderRadius: compact ? 18 : 0, justifyContent: `center`, borderColor: palette.line, backgroundColor: compact ? palette.paper : `transparent` },
  modes: { gap: 4, padding: condensed ? 0 : 4, borderWidth: 1, borderRadius: 10, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.input },
  mode: { gap: 7, flex: 1, minHeight: 44, borderWidth: 1, borderRadius: 8, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, borderColor: `transparent` },
  modeText: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  modeSelected: { borderColor: palette.line, backgroundColor: palette.paper },
  modeTextSelected: { color: palette.ink },
  heading: { gap: 8 },
  eyebrow: { color: palette.accent, fontSize: 10, letterSpacing: 1.6, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: compact ? 28 : 34, lineHeight: compact ? 32 : 40, letterSpacing: -1.2, fontFamily: `DMSans_700Bold` },
  description: { color: palette.muted, fontSize: 13, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  google: { gap: condensed ? 10 : 14 },
  emailDivider: { gap: 10, flexDirection: `row`, alignItems: `center` },
  dividerLine: { flex: 1, height: 1, backgroundColor: palette.line },
  dividerLabel: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_400Regular` },
  form: { gap: condensed ? 10 : 12 },
  field: { gap: condensed ? 5 : 6, minWidth: 0 },
  label: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  inputFrame: { gap: 12, minHeight: condensed ? 44 : 48, paddingHorizontal: 14, borderWidth: 1, borderRadius: 8, alignItems: `center`, flexDirection: `row`, borderColor: palette.line, backgroundColor: palette.input },
  input: { flex: 1, minWidth: 0, paddingVertical: condensed ? 9 : 12, color: palette.ink, fontSize: 16, fontFamily: `DMSans_400Regular` },
  toggle: { width: 44, height: 44, marginRight: -8, borderRadius: 8, alignItems: `center`, justifyContent: `center` },
  submit: { gap: 10, minHeight: condensed ? 44 : 48, paddingHorizontal: 20, borderRadius: 8, alignItems: `center`, flexDirection: `row`, justifyContent: `center`, backgroundColor: palette.accent },
  submitText: { color: palette.contrast, fontSize: 15, fontFamily: `DMSans_700Bold` },
  disabled: { opacity: 0.5 },
  reactivationPage: { minHeight: undefined },
  reactivation: { gap: 8, padding: 12, borderWidth: 1, borderRadius: 8, borderColor: palette.line, backgroundColor: palette.subtle },
  localNote: { gap: 9, paddingTop: 12, borderTopWidth: 1, flexDirection: `row`, alignItems: `center`, borderTopColor: palette.line },
  localCopy: { flex: 1, color: palette.muted, fontSize: 12, lineHeight: 20, fontFamily: `DMSans_400Regular` },
  loading: { gap: 16 },
  signedIn: { gap: 20, justifyContent: `center` },
  skeletonTitle: { height: 42, width: `75%`, borderRadius: 8, backgroundColor: palette.skeleton },
  skeletonCopy: { height: 18, width: `90%`, borderRadius: 5, backgroundColor: palette.skeleton },
  skeletonField: { height: condensed ? 44 : 48, borderRadius: 8, backgroundColor: palette.skeleton },
});
