import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  card: { gap: 12, padding: 14, borderWidth: 1, borderRadius: 12, borderColor: palette.line, backgroundColor: palette.paper },
  cardSelected: { borderColor: palette.accent, backgroundColor: palette.subtle },
  position: { minWidth: 20, textAlign: `center`, color: palette.muted, fontSize: 11, fontFamily: `DMSans_400Regular` },
  selectionPosition: { gap: 2, alignItems: `center` },
  selectionButton: { width: 32, height: 32, alignItems: `center`, justifyContent: `center` },
  selectionIcon: { backgroundColor: `transparent` },
  siteIcon: { width: 22, height: 22, resizeMode: `contain` },
  top: { gap: 8, flexDirection: `row`, alignItems: `center` },
  monogram: { width: 32, height: 32, borderRadius: 8, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  monogramText: { color: palette.accent, fontSize: 17, fontFamily: `DMSans_600SemiBold` },
  nameGroup: { gap: 4, flex: 1, minWidth: 0 },
  name: { flexShrink: 1, color: palette.accent, fontSize: 16, letterSpacing: -.3, fontFamily: `DMSans_600SemiBold` },
  nameLine: { gap: 6, flexDirection: `row`, alignItems: `center` },
  nameSeparator: { flexShrink: 0, color: palette.muted, fontSize: 12, fontFamily: `DMSans_400Regular` },
  siteLink: { gap: 5, flexShrink: 1, maxWidth: `100%`, flexDirection: `row`, alignItems: `center` },
  siteDescription: { flex: 1, minWidth: 0, color: `#ffffff`, fontSize: 12, fontFamily: `DMSans_400Regular` },
  owner: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_400Regular` },
  actionsCell: { gap: 3, flexDirection: `row` },
  actionButton: { padding: 7, borderRadius: 8, backgroundColor: palette.input },
  middle: { gap: 10, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  registrarGroup: { gap: 3, flex: 1, alignItems: `flex-start` },
  registrar: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_500Medium` },
  rowStatus: { gap: 6, flexDirection: `row`, alignItems: `center` },
  statusDotWrap: { width: 12, height: 12, borderRadius: 6, alignItems: `center`, justifyContent: `center` },
  statusDot: { width: 5, height: 5, borderRadius: 3 },
  statusText: { fontSize: 10, fontFamily: `DMSans_500Medium` },
  bottom: { gap: 10, paddingTop: 15, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  expiry: { gap: 4 },
  expiryDate: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_500Medium` },
  expiryDays: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_400Regular` },
  renewal: { gap: 5, alignItems: `flex-end` },
  renewalPrice: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_500Medium` },
  renewalEstimate: { gap: 5, paddingTop: 12, borderTopWidth: 1, borderTopColor: palette.line },
  renewalEstimateHeading: { gap: 10, flexWrap: `wrap`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  renewalEstimateLabel: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_500Medium` },
  renewalEstimatePrice: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  projectValue: { flexShrink: 1, maxWidth: `100%`, color: palette.ink, fontSize: 12, fontFamily: `DMSans_400Regular` },
  renewalEstimateHint: { color: palette.muted, fontSize: 9, lineHeight: 15, fontFamily: `DMSans_400Regular` },
  autoRenew: { gap: 4, flexDirection: `row`, alignItems: `center` },
  autoRenewText: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_400Regular` },
  skeletonHeader: { gap: 13, flexDirection: `row` },
  skeletonMonogram: { width: 40, height: 40, borderRadius: 12, backgroundColor: palette.skeleton },
  skeletonTitleGroup: { gap: 8, flex: 1, justifyContent: `center` },
  skeletonTitle: { width: `72%`, height: 13, borderRadius: 5, backgroundColor: palette.skeleton },
  skeletonOwner: { width: `45%`, height: 9, borderRadius: 4, backgroundColor: palette.skeleton },
  skeletonDetail: { width: `45%`, height: 12, borderRadius: 4, backgroundColor: palette.skeleton },
  skeletonFooter: { gap: 8, paddingTop: 15, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: `row`, justifyContent: `space-between` },
});
