import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  card: { gap: 18, padding: 19, borderWidth: 1, borderRadius: 18, borderColor: `#e3e7df`, backgroundColor: `#fffefa` },
  top: { gap: 13, flexDirection: `row`, alignItems: `center` },
  monogram: { width: 40, height: 40, borderRadius: 12, alignItems: `center`, justifyContent: `center`, backgroundColor: `#e8efea` },
  monogramText: { color: `#138b8b`, fontSize: 17, fontFamily: `DMSans_600SemiBold` },
  nameGroup: { gap: 4, flex: 1, minWidth: 0 },
  name: { color: `#133b50`, fontSize: 17, letterSpacing: -.3, fontFamily: `DMSans_600SemiBold` },
  owner: { color: `#8a938d`, fontSize: 11, fontFamily: `DMSans_400Regular` },
  actionsCell: { gap: 3, flexDirection: `row` },
  actionButton: { padding: 9, borderRadius: 8, backgroundColor: `#f4f5f0` },
  middle: { gap: 10, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  registrar: { color: `#61716f`, fontSize: 11, fontFamily: `DMSans_500Medium` },
  rowStatus: { gap: 6, flexDirection: `row`, alignItems: `center` },
  statusDotWrap: { width: 12, height: 12, borderRadius: 6, alignItems: `center`, justifyContent: `center` },
  statusDot: { width: 5, height: 5, borderRadius: 3 },
  statusText: { fontSize: 10, fontFamily: `DMSans_500Medium` },
  bottom: { gap: 10, paddingTop: 15, borderTopWidth: 1, borderTopColor: `#edf0e8`, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  expiry: { gap: 4 },
  expiryDate: { color: `#133b50`, fontSize: 12, fontFamily: `DMSans_500Medium` },
  expiryDays: { color: `#8a938d`, fontSize: 10, fontFamily: `DMSans_400Regular` },
  renewal: { gap: 5, alignItems: `flex-end` },
  renewalPrice: { color: `#133b50`, fontSize: 12, fontFamily: `DMSans_500Medium` },
  autoRenew: { gap: 4, flexDirection: `row`, alignItems: `center` },
  autoRenewText: { color: `#8a938d`, fontSize: 10, fontFamily: `DMSans_400Regular` },
  skeletonHeader: { gap: 13, flexDirection: `row` },
  skeletonMonogram: { width: 40, height: 40, borderRadius: 12, backgroundColor: `#e8ece5` },
  skeletonTitleGroup: { gap: 8, flex: 1, justifyContent: `center` },
  skeletonTitle: { width: `72%`, height: 13, borderRadius: 5, backgroundColor: `#e8ece5` },
  skeletonOwner: { width: `45%`, height: 9, borderRadius: 4, backgroundColor: `#e8ece5` },
  skeletonDetail: { width: `45%`, height: 12, borderRadius: 4, backgroundColor: `#e8ece5` },
  skeletonFooter: { gap: 8, paddingTop: 15, borderTopWidth: 1, borderTopColor: `#edf0e8`, flexDirection: `row`, justifyContent: `space-between` },
});
