import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  page: { gap: 28, padding: 24, justifyContent: `center` },
  intro: { gap: 14 },
  widePage: { gap: 36, flexDirection: `row`, alignItems: `center` },
  compactPage: { gap: 16, padding: 16, paddingVertical: 8 },
  wideIntro: { flex: .85 },
  wideReader: { flex: 1.15 },
  backLink: { gap: 7, minHeight: 28, alignSelf: `flex-start`, flexDirection: `row`, alignItems: `center` },
  backText: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_500Medium` },
  brandMark: { width: 52, height: 52, borderRadius: 14, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.subtle },
  heading: { gap: 12 },
  compactHeading: { gap: 7 },
  eyebrow: { color: palette.accent, fontSize: 9, letterSpacing: 1.2, fontFamily: `DMSans_700Bold` },
  title: { color: palette.ink, fontSize: 40, lineHeight: 46, letterSpacing: -1.2, fontFamily: `DMSans_700Bold` },
  compactTitle: { fontSize: 26, lineHeight: 30, letterSpacing: -.8 },
  description: { color: palette.muted, fontSize: 12, lineHeight: 18, fontFamily: `DMSans_400Regular` },
  reader: { gap: 24, padding: 24, borderWidth: 1, borderRadius: 16, borderColor: palette.line, backgroundColor: palette.paper },
  compactReader: { gap: 12, padding: 14, borderRadius: 12 },
  crampedReader: { gap: 10, padding: 12 },
  readerToolbar: { gap: 10, flexDirection: `row`, alignItems: `center` },
  toolbarTitle: { flex: 1, color: palette.ink, fontSize: 14, lineHeight: 18, fontFamily: `DMSans_700Bold` },
  topicScroll: { flexGrow: 0 },
  topics: { gap: 8, alignItems: `center` },
  topic: { minHeight: 36, borderRadius: 7, paddingVertical: 9, paddingHorizontal: 10, backgroundColor: palette.input },
  activeTopic: { backgroundColor: palette.subtle },
  topicText: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_500Medium` },
  activeTopicText: { color: palette.accent, fontFamily: `DMSans_700Bold` },
  section: { gap: 10 },
  sectionCount: { color: palette.accent, fontSize: 9, letterSpacing: 1, fontFamily: `DMSans_700Bold` },
  sectionTitle: { color: palette.ink, fontSize: 18, lineHeight: 23, fontFamily: `DMSans_700Bold` },
  tightSectionTitle: { fontSize: 16, lineHeight: 21 },
  sectionBody: { color: palette.muted, fontSize: 14, lineHeight: 23, fontFamily: `DMSans_400Regular` },
  compactBody: { fontSize: 13, lineHeight: 20 },
  readerNavigation: { gap: 8, paddingTop: 10, borderTopWidth: 1, borderTopColor: palette.line, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  crampedNavigation: { paddingTop: 0, borderTopWidth: 0 },
  readerButton: { gap: 7, minHeight: 36, paddingVertical: 7, paddingHorizontal: 8, borderRadius: 7, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.subtle },
  readerButtonText: { color: palette.ink, fontSize: 11, fontFamily: `DMSans_500Medium` },
  disabledButton: { opacity: .35 },
  detailCount: { color: palette.muted, fontSize: 11, fontFamily: `DMSans_400Regular` },
  contactLink: { gap: 10, minHeight: 36, paddingVertical: 9, paddingHorizontal: 14, borderRadius: 8, alignSelf: `flex-start`, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.strong },
  contactText: { color: `#ffffff`, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
});
