import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  checkedAt: { flex: 1 },
  disabled: { opacity: .5 },
  close: { padding: 8 },
  heading: { gap: 8, flex: 1 },
  body: { gap: 20, padding: 22 },
  loading: { gap: 16, paddingVertical: 16 },
  inline: { gap: 8, flexDirection: `row`, alignItems: `center` },
  backdrop: { ...StyleSheet.absoluteFillObject },
  section: { gap: 12, paddingTop: 18, borderTopWidth: 1, borderTopColor: palette.line },
  fields: { gap: 12, flexWrap: `wrap`, flexDirection: `row` },
  field: { gap: 5, flexGrow: 1, flexBasis: `43%` },
  keywords: { gap: 6, flexWrap: `wrap`, flexDirection: `row` },
  researchLinks: { gap: 8, flexWrap: `wrap`, flexDirection: `row` },
  actionsCell: { gap: 6, alignItems: `flex-start` },
  rowStatus: { gap: 7, flexDirection: `row`, alignItems: `center` },
  statusDotWrap: { width: 9, height: 9, alignItems: `center`, justifyContent: `center` },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  skeleton: { height: 110, borderRadius: 10, backgroundColor: palette.skeleton },
  dnsRecord: { gap: 10, padding: 10, borderRadius: 7, flexDirection: `row`, alignItems: `flex-start`, backgroundColor: palette.input },
  eyebrow: { gap: 8, flexDirection: `row`, alignItems: `center` },
  title: { fontSize: 25, color: palette.ink, fontFamily: `DMSans_700Bold` },
  note: { fontSize: 11, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  description: { fontSize: 12, lineHeight: 20, color: palette.muted, fontFamily: `DMSans_400Regular` },
  warning: { fontSize: 11, lineHeight: 18, color: palette.warning, fontFamily: `DMSans_400Regular` },
  error: { padding: 12, borderRadius: 7, fontSize: 12, lineHeight: 19, color: palette.danger, backgroundColor: palette.dangerBackground, fontFamily: `DMSans_400Regular` },
  sectionTitle: { fontSize: 14, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  fieldLabel: { fontSize: 10, color: palette.muted, fontFamily: `DMSans_400Regular` },
  fieldValue: { fontSize: 12, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  statusText: { fontSize: 11, fontFamily: `DMSans_600SemiBold` },
  dnsType: { width: 40, fontSize: 10, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  dnsValue: { flex: 1, fontSize: 11, lineHeight: 18, color: palette.ink, fontFamily: `DMSans_400Regular` },
  eyebrowText: { fontSize: 10, letterSpacing: 1.4, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  keyword: { fontSize: 11, borderRadius: 7, paddingVertical: 6, paddingHorizontal: 9, color: palette.accent, backgroundColor: palette.subtle, fontFamily: `DMSans_600SemiBold` },
  researchLinkText: { fontSize: 11, color: palette.accent, fontFamily: `DMSans_600SemiBold` },
  providerNote: { padding: 12, fontSize: 11, lineHeight: 19, borderRadius: 8, color: palette.muted, backgroundColor: palette.input, fontFamily: `DMSans_400Regular` },
  researchLink: { gap: 6, minHeight: 38, borderWidth: 1, borderRadius: 7, paddingVertical: 8, paddingHorizontal: 10, flexDirection: `row`, alignItems: `center`, borderColor: palette.line },
  refresh: { gap: 6, minHeight: 36, borderWidth: 1, borderRadius: 7, paddingVertical: 7, paddingHorizontal: 10, flexDirection: `row`, alignItems: `center`, borderColor: palette.line },
  header: { gap: 12, padding: 22, borderBottomWidth: 1, flexDirection: `row`, alignItems: `flex-start`, borderBottomColor: palette.line },
  footer: { gap: 12, padding: 16, borderTopWidth: 1, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between`, borderTopColor: palette.line },
  dialog: { width: `100%`, maxWidth: 620, maxHeight: `90%`, borderWidth: 1, borderRadius: 14, overflow: `hidden`, borderColor: palette.line, backgroundColor: palette.paper },
  overlay: { flex: 1, padding: 20, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.overlay },
});
