import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  shell: { flex: 1, backgroundColor: palette.canvas },
  scroll: { flex: 1 },
  blurTarget: { flex: 1 },
  content: { flexGrow: 1 },
  main: { width: `100%`, alignSelf: `stretch` },
  header: { gap: 8, zIndex: 40, paddingBottom: 16, paddingHorizontal: 24, borderBottomWidth: 1, borderBottomColor: palette.line, backgroundColor: `transparent` },
  stickyHeader: { top: 0, left: 0, right: 0, position: `absolute` },
  headerRow: { gap: 12, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center`, justifyContent: `space-between` },
  headerActions: { gap: 8, flexDirection: `row`, alignItems: `center` },
  logo: { width: 194, height: 58 },
  deviceBadge: { gap: 6, padding: 9, borderRadius: 6, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.subtle },
  deviceBadgeText: { color: palette.ink, fontSize: 9, letterSpacing: .5, fontFamily: `DMSans_700Bold` },
  navigation: { gap: 6, flexDirection: `row`, flexWrap: `wrap` },
  navigationLink: { gap: 7, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 6, flexDirection: `row`, alignItems: `center` },
  navigationLinkActive: { backgroundColor: palette.strong },
  navigationText: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  navigationTextActive: { color: `#ffffff` },
  navigationBetaText: { fontSize: 8, letterSpacing: .3, color: palette.accent, fontFamily: `DMSans_700Bold` },
  navigationBeta: { borderWidth: 1, borderRadius: 4, paddingVertical: 2, paddingHorizontal: 4, borderColor: palette.accent, backgroundColor: palette.subtle },
  footer: { gap: 10, minHeight: 64, paddingTop: 8, paddingHorizontal: 24, alignItems: `center`, flexDirection: `row`, borderTopWidth: 1, borderTopColor: palette.line },
  footerColumn: { flex: 1, minWidth: 0 },
  footerLinks: { gap: 6, flex: 1.35, flexDirection: `row`, justifyContent: `center` },
  footerLink: { gap: 4, minWidth: 44, minHeight: 44, flexDirection: `row`, alignItems: `center`, justifyContent: `center` },
  footerLinkText: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_500Medium` },
  copyright: { color: palette.muted, fontSize: 10, lineHeight: 15, fontFamily: `DMSans_400Regular` },
  footerAttribution: { flex: 1, minWidth: 0, alignItems: `flex-end` },
  piratechsLink: { color: palette.accent, fontFamily: `DMSans_500Medium` },
});
