import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  shell: { flex: 1, backgroundColor: palette.canvas },
  scroll: { flex: 1 },
  content: { flexGrow: 1 },
  main: { width: `100%`, alignSelf: `stretch` },
  header: { gap: 14, zIndex: 40, paddingBottom: 16, paddingHorizontal: 24, borderBottomWidth: 1, borderBottomColor: palette.line, backgroundColor: palette.paper },
  headerRow: { gap: 12, flexDirection: `row`, flexWrap: `wrap`, alignItems: `center`, justifyContent: `space-between` },
  headerActions: { gap: 8, flexDirection: `row`, alignItems: `center` },
  logo: { width: 194, height: 58 },
  deviceBadge: { gap: 6, padding: 9, borderRadius: 6, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.subtle },
  deviceBadgeText: { color: palette.ink, fontSize: 9, letterSpacing: .5, fontFamily: `DMSans_700Bold` },
  navigation: { gap: 6, flexDirection: `row`, flexWrap: `wrap` },
  navigationLink: { gap: 7, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 6, flexDirection: `row`, alignItems: `center` },
  navigationLinkActive: { backgroundColor: palette.strong },
  navigationText: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  navigationTextActive: { color: `#ffffff` },
  footer: { gap: 20, marginTop: 18, paddingTop: 24, paddingHorizontal: 24, borderTopWidth: 1, borderTopColor: palette.line },
  footerTop: { gap: 16, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  footerLabel: { color: palette.ink, fontSize: 13, fontFamily: `DMSans_600SemiBold` },
  footerDevice: { gap: 6, flexDirection: `row`, alignItems: `center` },
  footerDeviceText: { color: palette.muted, fontSize: 10, fontFamily: `DMSans_500Medium` },
  footerLinks: { gap: 18, flexWrap: `wrap`, flexDirection: `row` },
  footerLink: { gap: 6, paddingVertical: 4, flexDirection: `row`, alignItems: `center` },
  footerLinkText: { color: palette.muted, fontSize: 12, fontFamily: `DMSans_500Medium` },
  copyright: { color: palette.muted, fontSize: 11, lineHeight: 18, fontFamily: `DMSans_400Regular` },
  piratechsLink: { color: palette.accent, fontFamily: `DMSans_500Medium` },
});
