import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../shared/themeContext/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  root: { gap: 36, paddingVertical: 48, paddingHorizontal: 24, flexDirection: `row`, width: `100%`, maxWidth: 1160, alignSelf: `center` },
  compact: { gap: 24, paddingVertical: 28, flexDirection: `column` },
  content: { gap: 14, flex: 1, minWidth: 0 },
  sidebar: { gap: 12, width: 190, paddingTop: 6 },
  compactSidebar: { width: `100%`, flexDirection: `row`, alignItems: `center`, flexWrap: `wrap` },
  eyebrow: { fontSize: 10, letterSpacing: 1.6, color: palette.muted, fontFamily: `DMSans_700Bold` },
  title: { fontSize: 38, color: palette.ink, letterSpacing: -1.2, fontFamily: `DMSans_700Bold` },
  description: { fontSize: 13, lineHeight: 22, color: palette.muted, marginBottom: 16, fontFamily: `DMSans_400Regular` },
  link: { gap: 9, padding: 12, borderRadius: 6, flexDirection: `row`, alignItems: `center` },
  linkText: { color: palette.ink, fontSize: 12, fontFamily: `DMSans_600SemiBold` },
  activeLink: { backgroundColor: palette.subtle },
  panel: { gap: 18, padding: 24, borderRadius: 12, backgroundColor: palette.paper, borderWidth: 1, borderColor: palette.line },
  panelTitle: { fontSize: 15, color: palette.ink, fontFamily: `DMSans_700Bold` },
  field: { gap: 6, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: palette.line },
  label: { fontSize: 11, lineHeight: 18, color: palette.muted, fontFamily: `DMSans_400Regular` },
  value: { fontSize: 13, lineHeight: 20, color: palette.ink, fontFamily: `DMSans_600SemiBold` },
  note: { gap: 10, flexDirection: `row`, alignItems: `center` },
  noteText: { flex: 1, fontSize: 11, lineHeight: 19, color: palette.muted, fontFamily: `DMSans_400Regular` },
  stats: { gap: 12, flexDirection: `row`, flexWrap: `wrap` },
  stat: { gap: 10, flexGrow: 1, flexBasis: 140, padding: 20, borderRadius: 10, backgroundColor: palette.paper, borderWidth: 1, borderColor: palette.line },
  statValue: { fontSize: 25, color: palette.ink, fontFamily: `DMSans_700Bold` },
  skeleton: { height: 28, width: `75%`, borderRadius: 5, backgroundColor: palette.skeleton },
  roleRow: { gap: 8 },
  track: { height: 8, borderRadius: 8, overflow: `hidden`, backgroundColor: palette.subtle },
  bar: { height: 8, borderRadius: 8, backgroundColor: palette.accent },
  userRow: { gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: palette.line, flexDirection: `row`, alignItems: `center`, flexWrap: `wrap` },
  userDetails: { gap: 3, flex: 1, minWidth: 120 },
  statusCell: { gap: 7, flexDirection: `row`, alignItems: `center` },
  dot: { width: 6, height: 6, borderRadius: 6 },
  error: { color: palette.danger, fontSize: 12, fontFamily: `DMSans_400Regular` },
});
